{
  "hash": "c9d0e8ce65bd3ff94b27b91c353e15de",
  "result": {
    "markdown": "---\ntitle: Stellar properties\nauthor:\n  name: Dr Rosaria Lena\n  affiliation: rosaria.lena@glasgow.ac.uk\ndate: last-modified\ndate-format: long\naffiliation-title: email\ndescription: _Lectures 1-3_ (part 1.1).\ntitle-block-banner: true\nexecute:\n  echo: true\n  freeze: auto\n---\n\n-----------\n\n\n# Look at the night sky, what do we see?\n\nLet's start with some simple observations of the night sky...\n\n\"Look at the night sky, what do we see?\"\n\nHere in Scotland, the answer to this questions is likely 'clouds', but if you are curious to know what is beyond those clouds, you can check out Stellarium (you can download it or you can use the [web version](https://stellarium-web.org/)).\n\nAll that glitters is not (only) stars!\n\n![An example of the night sky view taken from Stellarium](img/Stellarium_full.png){#fig-Stellarium}\n\nLooking at the night sky we may be able to see planets, meteors, galaxies, satellites, comets, star clusters and many stars!\n\n![An example of the night sky view taken from Stellarium (with marked typical objects)](img/Stellarium_full_description.png){#fig-Stellarium-marked}\n\n# What is a star?\nA star is an astronomical spheroid body:\n\n- held together by _self-gravity_\n- _radiating_ energy from an internal source (tipycally from nuclear fusion reactions, and occasionally from the release of gravitational potential energy during contraction or collapse)\n\nHaving this definition you should be able to answer the following questions:\n\n1. Is the Death Star a (fictional) star?\n\n<details>\n<summary> Answer </summary>\nThe answer is \"no\", because it does not radiate energy! The Death Star is actually a (fictional) space station orbiting the (fictional) planet moon of Endor.\nEnough with the fictional stuff now.\n</details>\n\n2. If you look at the sky you may see that planets and comets are also shining in the sky, so why can't they be considered stars, based on the definition given above? Do they radiate energy? Are they self-gravitating?\n\n<details>\n<summary> Answer </summary>\nPlanets actually do not _radiate_, they mostly reflect the light coming from the Sun, and the same holds for comets. In addition to that, comets do not have enough mass to be considered self-gravitating objects.\n</details>\n\n\n## Life and death of a star\nA star is not a static object. During its life it will evolve, changing its internal structure and chemical composition as it 'burns its _fuel_' and changing its mass and size.\n\nThe death of a star eventually occurs when one of the conditions that define a star is no longer valid, i.e. when the star is no longer self-gravitating, or when it stops radiating having exhausted its nuclear fuel.\n\nWe will talk more about the evolution of stars in the following lectures.\nNow let's go back to what we can observe having a look at the night sky and let's see what we can tell from observations of stars.\n\n## Do all stars look the same?\n<img src=\"img/intro2.png\" width=\"600\" height=\"600\"/>\n\n![Examples of stars](img/M3_color3.gif)\n\n- There are a lot of stars, not uniformly distributed\n- Some look brighter than others\n- Some are bigger than others\n- They have different colours\n- Sometimes there are coloured or dark areas around stars\n- Some stars have fluctuating brightness: repeating and irregular\n\n## A comparison between two stars on Stellarium\n\nLet's check the properties of two stars on Stellarium. What can you notice after a first look at these stars in  @fig-Stellarium-stars-compare?\nYou may notice that they have different colours (one looks white, the other one looks white-blue). The boxes contain some information about these stars, and you may recognise many of these fields in the blue boxes from positional astronomy. We will find out what the properties in the red boxes mean during this course.\n\n![Comparison between two stars on Stellarium](img/Stellarium_stars_p.png){#fig-Stellarium-stars-compare}\n\n## What can we tell from observations?\n\n- How distant are the stars?\n- How big are they?\n- How bright?\n- How, when and where do they form?\n- What are their most important characteristics?\n- What are they made of?\n- What is their energy source?\n- What happens when it runs out?\n\n# How distant are the stars?\n\n## An easy case: the distance to the Sun\n\n__How do we find the distance to the Sun?__\n\nEasy! - Just define The Astronomical Unit (a.u.) as the average distance between the Earth and the Sun!\n\n## The astronomical unit\n\nOk, but how big is an au?\nIn 1976 the International Astronomical Union (IAU) adopted a standard definition whose value has been updated with increasing precision  during the years. At the current date, the astronomical unit has the following value.\n\n::: {.callout-note appearance=\"simple\"}\n## Astronomical unit value\n1 a.u. = 149,597,870,700 m\n:::\n\n### <span style=\"color:#336699;\">Question</span>\n\nCan you now work out how long it takes for the sunlight to reach Earth?\n\n<details>\n<summary> Solution </summary>\n\n::: {.cell slideshow='{\"slide_type\":\"fragment\"}' execution_count=1}\n``` {.python .cell-code}\nimport math\nAU = 149597870 # km\nc = 299792.458 # km/s\nts = AU/c # s\ntm = ts/60 # min\nprint(f\"Time taken by light to reach Earth from the Sun = {ts:1.4} s = {tm:1.4} min = 8 min 19 s \")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTime taken by light to reach Earth from the Sun = 499.0 s = 8.317 min = 8 min 19 s \n```\n:::\n:::\n\n\n</details>\n\n### A remark on the Astronomical Unit\n\nNote: 1 a.u. is an _average_ distance, because the distance between the Earth and the Sun varies during the year.\n\n\n![Illustration of the perhelion and aphelion in Earth's orbit around the Sun](img/Earth-orbit-Sun_fixed.png){#fig-perhelion-aphelion}\n\n<!-- <div>\n<img src=\"img/Earth-orbit-Sun_fixed.png\" width=\"700\" height=\"500\"/>\n</div> -->\n\n::: {.cell slideshow='{\"slide_type\":\"fragment\"}' execution_count=2}\n``` {.python .cell-code}\nimport math\nAU = 149597870 # km\naphD = 152100000 # km\nperD = 147100000 # km\nAU_avg = (aphD+perD)/(2*AU) # Average distance, gives AU, check: print(f\"{AU_avg}\")\nprint(f\"Distance Earth-Sun at aphelion (most distant) = {aphD:1.3e} km = {aphD/AU:1.4} au\")\nprint(f\"Distance Earth-Sun at perihelion (closest) = {perD:1.3e} km = {perD/AU:1.3} au\")\nprint(f\"Average distance Earth-Sun = {AU:1.3e} km = 1 au\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistance Earth-Sun at aphelion (most distant) = 1.521e+08 km = 1.017 au\nDistance Earth-Sun at perihelion (closest) = 1.471e+08 km = 0.983 au\nAverage distance Earth-Sun = 1.496e+08 km = 1 au\n```\n:::\n:::\n\n\n## Size of our solar system\n\n\n| Planet | Distance from Sun (a.u.) |\n| ------ | ----------------- |\n| Mercury | 0.39 |\n| Venus | 0.72 |\n| Earth | 1 |\n| Mars | 1.52 |\n| Jupiter | 5.20 |\n| Saturn | 9.54 |\n| Uranus | 19.2 |\n| Neptune | 30.06 |\n\n![Distances in the solar system. Planet sizes are not to scale.](img/Solar_system_distances.png){#fig-solar-distances}\n\n<!-- \n<img src=\"img/Solar_system_distances.png\" style=\"max-height: 300px; base64; display: block; position:relative; float:centre; padding-right:0.5cm\"/> -->\n    \n\n## Measuring the distance to the stars\n### The parallax method\n\nWe started with the easy example of answering how distant is the Sun, but what about other stars? One way to determine the distance to nearest stars is to use the _parallax method_.\n\nIf you look at the position of a closer object against a further background, you will notice that the image of the near object will shift in the background as you move (see @fig-parallax1). This effect is called parallax and you can experience it even when you close one eye at the time looking at an object against a background.\n\n<!-- <div>\n<img src=\"img/Parallax_Example.png\" width=\"700\"/>\n</div> -->\n![Illustrative example of the parallax method. The background against which the yellow star object is seen changes based on the viewpoint.](img/Parallax_Example.png){#fig-parallax1}\n\nAnalogously, in a background of distant stars, a closer star will appear to move against them as the Earth orbits the Sun. So how do we use this to determine the distance to a start? We use trigonometry.\n\nThe angle formed between the lines of sight of a star from two positions of the observer is twice the parallax angle.\n@fig-parallax2 shows the parallax as the angle between the lines of sight of the observer on Earth and from the Sun (the middle point between the position of Earth six months apart).\n\nThe number of stars that can be observed from Earth is limited and nowadays _direct_ observations of the distance using the parallax method are done by satellites orbiting the Sun in sync with Earth. Hipparcos gathered data on more than one million stars, and its successor Gaia has already observed 2 billion stars!\n\n<!-- <img src=\"img/parallax_parsecs.webp\" style=\"max-height: 600px; display: block; position:relative; float:right; padding-left:.5cm\"> -->\n\n![Parallax and parsecs representation. Image readapted from: https://www.astronomy.com/wp-content/uploads/sites/2/2023/02/parsec.png](img/parallax_parsecs.png){#fig-parallax2}\n\n<!-- $\\begin{equation} -->\n    \n<!-- \\end{equation}$ -->\n\n- The parallax is generally measured in arcseconds (_as_).\n\n:::{.callout-note appearance=\"simple\"}\n## Arcseconds - degrees - radians conversion\n$$\n  \\mathrm{1 arcsecond} = \\dfrac{1}{3600} \\deg = \\dfrac{1}{206,265} \\mathrm{radians}.\n$$\n\nYou can show these conversions by recalling that\n$$\n  1\\ \\mathrm{rad} = 57.3\\deg = (57.3\\times 60\\times 60)\\ \\mathrm{as}=206,265\\ \\mathrm{as}.\n$$\n\n:::\n\n:::{.callout-note appearance=\"simple\"}\n## Parsec definition\n- The parsec (**par**allax-**sec**ond, _pc_) is defined as:\n\n\\begin{align*}\n1\\ \\mathrm{parsec} &= \\dfrac{1 \\mathrm{au}}{\\mathrm{arcsecond\\  in\\  radians}} = 206,265\\mathrm{au}= \\dfrac{648000}{\\pi} \\mathrm{au}\\\\\n &\\approx 3.086\\times 10^{16}\\mathrm{m}.\n\\end{align*}\n:::\n\n- A parallax of 1 arcsecond corresponds to a distance to the star of 1 parsec (3.26 light-years).\n\n- Using trigonometry, the distance $d$ to the star, in astronomical units, is given by:\n\n$$\n    d =\\dfrac{1 \\mathrm{au}}{\\tan p}\\simeq \\dfrac{1}{p} \\mathrm{au} \n$$\nwhere $p$ is the parallax, and for this approximation we used $p$ measured in radians.\nConverting the parallax $p$ to $p''$, from radians to arcseconds, we obtain the distance in parsec:\n$$\n    d \\simeq\\dfrac{206,265 \\mathrm{au}}{p''}= \\dfrac{1}{p''} \\mathrm{pc} \n$$\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nimport math\nAU = 149597870 # km\npc = 648000/np.pi*AU # km\nprint(f\"1parsec = {pc:1.3e} km\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1parsec = 3.086e+13 km\n```\n:::\n:::\n\n\n### The nearest star: Proxima Centauri\n\nThe further a star is, the smaller the parallax angle.\n\nThe nearest star (Proxima Centauri) has a parallax of 0.7681 arcseconds. This is _very_ tiny, but still, we are able to measure it! To give you an idea of how small this is:\n\n- It is approximately the angle subtended by an object having a diameter of 2 centimeters, positioned at a distance of 5.3km!\n- The shift produced by the parallax against the background would be $1/2000^{th}$ the width of the Full Moon!\n\nThe parallax method is covered in other courses, so this is just a taster, but now knowing the parallax of Proxima Centauri (or another star), we can find the distance to that.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nimport math\nimport numpy as np\ndef arcsec_to_rad(p):\n    rad = p/206265\n    return rad\n\np = 0.7681 # as\nd_pc = 1/p # pc\n\np_rad = arcsec_to_rad(p)\nd_au = 1/p_rad # au\nd_km = d_au*AU # km\nprint(f\"p = {p} as\")\nprint(f\"d = 1/p pc = 1/{p} pc = {d_pc:1.1e} pc\")\nprint(f\"d = 1/p pc = 206265/p au = 206265/{p} au = {d_au:1.1e} au\")\nprint(f\"d = {d_au:1.1e} au * 149597870 km = {d_km:1.1e} km\")\nprint(f\"The distance from Proxima Centauri is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\np = 0.7681 as\nd = 1/p pc = 1/0.7681 pc = 1.3e+00 pc\nd = 1/p pc = 206265/p au = 206265/0.7681 au = 2.7e+05 au\nd = 2.7e+05 au * 149597870 km = 4.0e+13 km\nThe distance from Proxima Centauri is = 1.3e+00 pc = 2.7e+05 au = 4.0e+13 km\n```\n:::\n:::\n\n\n### <span style=\"color:#336699;\">'Spot the mistake' question:</span>\nAn unknown star has a parallax of 379.21 mas. Your messy lecturer tried to calculate the distance to the star but she must have made some mistakes because something looks wrong. Can you tell what?\n\n```python\n# This is the version with mistakes\nimport math\n\np = 379.21/10000 # as \nd_pc = 206265/p # pc\n\nd_au = 1/p # au\n\nAU = 149597870 # km\nd_km = d_au*AU # km\nprint(f\"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km? Something does not look right... find the mistakes!\")\n```\nThe distance to the star is = 5.4e+06 pc = 2.6e+01 au = 3.9e+09 km? Something does not look right... find the mistakes!\n\n::: {.callout-tip collapse=\"true\"}\n## Hints\n\n<details>\n<summary>Hint 1</summary>\nCheck the orders of magnitude, do they seem reasonable?\n</details>\n<details>\n<summary>Hint 2</summary>\nCompare these orders of magnitude with the ones found for Proxima Centauri, any red flags?\n</details>\n<details>\n<summary>Hint 3</summary>\nThe units are important!\n</details>\n\n:::\n\n<!-- ```{python}\n# The version with mistakes, where I made a wrong units conversion and I swapped the formulas for d in pc and in au\nimport warnings\nwarnings.filterwarnings('ignore')\nimport math\n\np = 379.21/10000 # as \nd_pc = 206265/p # pc\n\nd_au = 1/p # au\n\nAU = 149597870 # km\nd_km = d_au*AU # km\nprint(f\"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km? Something does not look right... find the mistakes!\") -->\n\n<details>\n<summary> __Solution__ </summary>\n\nBelow is the solution to the question. Something was clearly wrong with the orders of magnitudes of the values obtained in the wrong solution:\n\n- the distance in pc can not be larger than the distance in au! Those orders of magnitude are clearly off!\n- if you compare this with the values obtained for Proxima Centauri, you should expect approximately the same orders of magnitude\n- $10^6$ pc would be way too far to be able to use the parallax method to measure the distance: the most precise and reliable measurements of the parallax (with the Hubble Space Telescope and Gaia space mission), can measure distances of the order of $10^3\\mathrm{pc}$.\n\n<!-- ```python \n# The correct version\nimport warnings\nwarnings.filterwarnings('ignore')\nimport math\n\np = 379.21/1000 # as <- the units conversion was wrong\nd_pc = 1/p # pc <- This formula for the distance in pc was swapped with the one below for the distance in au\n\nd_au = 206265/p # au <-\n\nAU = 149597870 # km\nd_km = d_au*AU # km\nprint(f\"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km\n```\nThe distance to the star is = 2.6e+00 pc = 5.4e+05 au = 8.1e+13 km -->\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\n# The correct version\nimport math\n\np = 379.21/1000 # as <- the units conversion was wrong\nd_pc = 1/p # pc <- This formula for the distance in pc was swapped with the one below for the distance in au\n\nd_au = 206265/p # au\n\nAU = 149597870 # km\nd_km = d_au*AU # km\nprint(f\"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe distance to the star is = 2.6e+00 pc = 5.4e+05 au = 8.1e+13 km\n```\n:::\n:::\n\n\n</details>\n\n## Transit method\n\n<img src=\"img/HalGreg.jpg\" style=\"max-height: 200px; display:block; position:relative; float:left; padding-right:1cm\">\nThe parallax was also originally proposed as a way to determine the distance to the Sun by the Scottish astronomer James Gregory, in 1663, using the transit of Venus. Gregory is seldom given any credits for this idea and usually all the credits goes to Edmund Halley for some reason (can anyone find out why?).\n\nIn 1677, at the age of 20, Halley travelled to St Helena to map the Southern Skies and observed a transit of Mercury on November 7th.\nLike Gregory, he suggested that the transit of a planet like Venus could be used as a method to measure the distance to the Sun, using parallax.\n\n[Here](https://eclipse.gsfc.nasa.gov/transit/HalleyParallax.html) is the translation of Halley's publication about this idea.\n\n![A composite image of the June 2004 transit of Venus as seen from Waldenburg, Germany. Credit: E. SLAWIK/SPL](img/VenusTransit.png){#fig-Venus-transit}\n\n\n<!-- <img src=\"img/VenusTransit.png\" style=\"max-height: 500px; display: block; position:relative; float:left; padding-right:1cm\"> -->\n\n\n![Representation of the transit method](img/TransitMethod.png){#fig-transit-method}\n\nAccording to 'Halley's method', two observers (A and B in the figure above) have to be positioned at a great distance from each other, but both located on the side of Earth facing the Sun at the time of the transit. Each observer would precisely measure the times that Venus appear to be in different positions (contact points) relative to the Sun. The observers would see different chords of the planet's trajectory across the disk of the sun due to parallax. \nVenus forms two similar triangles with the Earth and the Sun at their opposite edges. Since the triangles are similar, the projected distance on the Sun can be found by comparing it to a known baseline on Earth. Once the angle shift is measured, the distances to Venus and then to the Sun can be determined using trigonometry.\n\nModern techniques use radar echo ranging to measure distances in the Solar System very precisely.\n\n<!-- Venus forms two similar triangles with the Earth and the Sun at their opposite edges. Since the triangles are similar, the projected distance on the Sun can be found by comparing to a known baseline on Earth. -->\n\n# How big are stars?\n\n## How big is the Sun?\n\n<!-- ![](img/AngularDiameter.png){#fig-angular-diameter width=25% fig-align=\"right\" fig-alt=\"Geometrical configuration of the Sun as seen from an observer at distance D.\"} -->\n\n<img style=\"float: right; max-height: 350px; position:relative;\" src=\"img/AngularDiameter.png\">\n\n\nWe can deduce the width of the sun if we know its angular diameter $\\alpha$ and the distance $D$.\n\nFor small angles,\n\n$$\n \\alpha \\approx \\frac{2R_\\odot}{D}.\n$$\n\n:::{.callout-warning}\nThis formula uses _radians_ for $\\alpha$\n:::\n\nSince the Sun's angular diameter is $\\alpha\\approx 0.5^\\circ \\approx 32 \\ \\mathrm{arcmin} \\approx 9.3\\times 10^{-3} \\mathrm{rad}$,\nand we know its distance (from Earth)\n$D = 1 \\mathrm{au} = 149,597,870 \\ \\mathrm{km}$, we can now calculate the size of the Sun using the equation above.\n\n::: {.cell slideshow='{\"slide_type\":\"fragment\"}' execution_count=6}\n``` {.python .cell-code}\nimport math\nAU = 149597870 # km\nang_diameter_arcm = 32 # angular diameter of Sun is about 32 minutes of arc\nang_diameter = ang_diameter_arcm/60 * math.pi/180 \n# ang_diameter = ang_diameter_rad\ndiameter = AU * ang_diameter\nprint(f\"1 au = {AU:1.3e} km\")\nprint(f\"angular diameter of the sun =  {ang_diameter:.3e} radians\")\nprint(f\"Diameter of Sun = {diameter:.0f} km\")\nprint(f\"Radius of Sun = {diameter/2:.0f} km\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1 au = 1.496e+08 km\nangular diameter of the sun =  9.308e-03 radians\nDiameter of Sun = 1392520 km\nRadius of Sun = 696260 km\n```\n:::\n:::\n\n\nThe accepted radius is $6.957\\times 10^5$ km.\n\n## What about other stars?\n\nHere is a video showing a comparison between star sizes: https://www.youtube.com/watch?v=HEheh1BH34Q\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/HEheh1BH34Q?si=BQb-tLiTvei87S7Q\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\n\n### A comparison of some star sizes\n\nHere is a list of some selected examples of star radii, compared to the Sun.\nSome stars, such as Sirius B, are much smaller than the Sun. (@fig-siriusAB below shows an artistic impression of Sirius A and Sirius B.)\n\nThe typical range of star radii is roughly $10^{-3}R_\\odot < R < 10^3 R_\\odot$.\n\n| Name | Radius |\n|------|--------|\n| Sirius B | 0.008 $R_\\odot$|\n| Sirius A | 1.71 $R_\\odot$|\n| Arcturus | 12 $R_\\odot$ |\n| Aldebaran | 22 $R_\\odot$ |\n| Rigel | 78.9 $R_\\odot$|\n| Mira | 210 $R_\\odot$ |\n| Betelgeuse | 320 $R_\\odot$ |\n\n<!-- <img src=\"img/siriusAB.jpeg\" style=\"max-height: 500px; display: block; position:relative; float:right; padding-right:1cm\"> -->\n\n![Artistic impression of Sirius A (large blue-white star on the left) and Sirius B (small blue white-dwarf star on the right). _Image credit: NASA, ESA and G. Bacon (STScI)_](img/siriusAB.jpeg){#fig-siriusAB}\n\n\n- Sirius B is a very small but very hot white dwarf. It is even smaller than Earth, and it cannot be observed by the naked eye. Its companion star Sirius A, in contrast, is the brightest star in the sky\n- Betelgeuse – at a distance of 650 l.y. is a red supergiant and rather short-lived star, the second brightest in Orion and the ninth brightest in the sky\n- It’s close to the end of its life and en-route to a rather spectacular death within  a million years or so\n- For Betelgeuse, the angular diameter $\\alpha$ is about 0.000014 degrees ($1.4\\times 10^{-5}$ degrees)\n- Most stars have a much smaller angular diameter and cannot be directly imaged\n- We have to deduce their size indirectly! (more on this later)\n\n![Betelgeuse. _Image credit: ALMA (ESO/NAOJ/NRAO)/E. O'Gorman/P. Kervella_](img/Betelgeuse.png){#fig-betelgeuse}\n\n\n## A handy guide to estimating angular diameters\n\nYou can estimate angular diameters using your hand! Extend your arm, place the hand at a right angle and follow the intstructions of @fig-handy-guide to estimate different angles.\nThis may not be useful to determine the size of objects that are very far and appear too small, such as stars, but can be useful to measure the angular distance between two stars.\n\n![How to use hands to measure angular distances in the sky](img/measuring-sky-with-hand.png){#fig-handy-guide}\n\n## How far apart are the stars?\n\nLet's have a look at some orders of magnitude (this is a good resource if you want to visualise them: https://scaleofuniverse.com/en-gb).\n\n- The nearest star (Proxima Centauri) is about $10^{16}$ m away.\n- Diameter of the Sun ~ $10^{9}$ m.\n- The difference in scale is $10^7$m in distance, or $10^{21}$m$^3$ in volume.\n- Relative to their size, stars are the most isolated structures in the universe.\n- If stars were grains of sand (~1 mm), they would be ~10 km apart!\n- However, we find them in clusters and binaries - what explains this? (more on this later)\n\n# How bright are stars?\n\nIf we try to answer this question based on our observations, we have to keep in mind that the apparent brightness of a light source will vary depending on its distance from the observer. The brightenss we observe is therefore not an _intrinsic_ property of the stars, as it depends on the distance between the observer and the stars.\n\nThis is the reason why we need to differentiate between the _apparent brightness_ of a star and its _luminosity_.\n\n## Apparent brightness and luminosity\n\nThe __apparent brightness__, $F$, also referred to as the _radiant flux_ or _power flux_, is the total amount of energy emitted by a star, per unit time, crossing an unit area (units [$\\mathrm{W/m}^2$]).\nIt is _not_ an intrinsic property of a star, because it depends on the distance from the star.\n \n@fig-inverse-square-law can give you a better understanding of that. Each square represents an unit area. The lightbulb, like a star, radiates equally in every direction (i.e. isotropically). The 'rays' coming out of the light source represent the flux. The farther the position of the observer is from the source, the less flux the observer, in one unit area, will receive. The relationship between the power flux, $F$, and the distance to the source, $r$, is given by the inverse square law: $$F\\propto \\dfrac{1}{r^2}.$$\nSince the light source radiates isotropically (even though the figure below shows only a portion of the rays), the power flux $F$ is equal across all parts of the sphere at a given distance.\n\n![Inverse square law of the radiant flux of a light source](img/inverse_square_law.png){#fig-inverse-square-law}\n\nThe __Luminosity__ of a star, $L$, measured in Watts (W) or equivalently Joules per second (J/s), is its energy output per unit time. The luminosity is the _total_ energy radiated in all the directions in an unit time and it does not depend on the distance from the observer: it is an _intrinsic_ property of the star.\n\nHow are these two quantities related?\n\nImagine a sphere of radius $r$ centered on a star, which is isotropically radiating. We saw that the luminosity (energy output per unit time) does not depend upon the distance, but the radiant flux $F$ does. To find the power flux $F$, we need to divide the luminosity equally over the area of the sphere, $4\\pi r^2$. Therefore\n$$\nF = \\frac{L}{4\\pi r^2}\n$${#eq-flux}\n\nThe apparent brightness depends on the luminosity and on the distance of the observer from the star. From @eq-flux, you can see how two stars of equal luminosity, located at different distances from Earth, would have different apparent brightness.\n\n_Photometry_ is the measurement of the quantity of light from a star, i.e. the flux of energy per unit time, per unit area, that we receive at Earth.\n\nFor a particular star, if we know the luminosity ($L$) of the star and its distance from Earth ($r$), we can calculate the radiant flux using @eq-flux.\n\n### The Sun's luminosity\n\nFor our Sun, we have:\n\n$F_\\odot = 1361\\,  \\mathrm{W/m^2}$ (The \"Solar Constant\", or \"Solar irradiance\", sometimes indicated with the symbol $S_\\odot$ in textbooks), and\n\n$r = 1\\, \\mathrm{a.u.} \\approx 1.5\\times 10^{11}\\mathrm{m}$.\n\nTherefore, using @eq-flux:\n\n$L_\\odot = 4\\pi r^2 F = 3.8275 \\times 10^{26}\\, \\mathrm{W}$\n\n::: {.cell slideshow='{\"slide_type\":\"skip\"}' execution_count=7}\n``` {.python .cell-code}\nimport scipy\nfrom scipy.constants import pi, au, parsec\n\nF = 1361.0 # W/m/m\nr = au # m\nL = F*4*pi*r**2\n\nprint(f'Power flux: F = {F} W/m/m')\nprint(f'r = 1au = {r:1.4e} m')\nprint(f'Luminosity: L =  F*4*pi*r**2 = {L:1.4e} W')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPower flux: F = 1361.0 W/m/m\nr = 1au = 1.4960e+11 m\nLuminosity: L =  F*4*pi*r**2 = 3.8275e+26 W\n```\n:::\n:::\n\n\nFor other stars there is a large range of luminosities:\n\n$10^{-4}\\,L_\\odot < L < 10^{6}\\,L_\\odot$\n\nIf we think of the least luminous star as a 100W incandescent lightbulb, this huge range tells us that the most luminous star would be like the entire world’s power output.\n\nWhy is there this very large range? We will answer this question in the next lectures.\n\n### <span style=\"color:#336699;\">'Spot the mistake' question:</span>\nWhat would the apparent brightness be for a star like the Sun at a distance of 10 pc?\n\nSomething does not seem to make sense in the answer below, why?\n\n```python\n# This is the version containing a mistake\nimport math\nimport numpy as np\nL = 3.8275E26 # W\nr = 10 #pc\nF = L/(4*np.pi*r**2) # W/m^2\nprint(f'Solar luminosity: L = {L} W')\nprint(f'Distance: r = {r} pc')\nprint(f'Apparent brightness of the Sun at 10 parsec: F = L/(4*pi*r^2) = {F:1.4e} W/m/m')\n```\n\nSolar luminosity: L = 3.8275e+26 W\n\nDistance: r = 10 pc\n\nApparent brightness of the Sun at 10 parsec: $F = \\frac{L}{4\\pi r^2} = 3.0458\\times 10^{23} W/m^2$\n\n<!-- ```python\n# This is the version containing a mistake\nL = 3.8275E26 # W\nr = 10 #pc\nF = L/(4*pi*r**2)\nprint(f'Solar luminosity = {L} W')\nprint(f'Distance r = {r} pc')\nprint(f'Apparent brightness of the Sun at 10 parsec: F = {F} W/m/m') -->\n<!-- ```\nSolar luminosity = 3.8275e+26 W\nDistance r = 10 pc\nApparent brightness of the Sun at 10 parsec: F = 3.0458e+23 W/m/m\n``` -->\nDoes this make sense?\n\n::: {.callout-tip collapse=\"true\"}\n## Hints\n<details>\n<summary>Hint 1</summary>\nCompare this apparent brightness obtained below with the value of the power flux used (the Solar constant) in the previous example. What is wrong?\n</details>\n<details>\n<summary>Hint 2</summary>\nDo a 'sanity check' of the units in the quantities used above. Does it seem correct?\n</details>\n:::\n\n<details>\n<summary>Solution</summary>\nIf we compare this value obtained for the apparent brightness, $F=3.046\\times 10^{23} \\mathrm{W/m}^2$, with the Solar constant used in the previous example, $F_\\odot = 1361 \\mathrm{W/m}^2$, we can immediately notice that something is wrong by just looking at the extreme difference in the orders of magnitude. If we are observing the Sun from a further position of 10pc instead of 1au, we cannot expect it to appear brighter!\n\n_'Sanity check'_: Let's check the units of the quantities given above, replacing them in @eq-flux:\n$$ F=\\frac{L}{4\\pi r^2} \\implies [W/m^2] = \\frac{[W]}{[pc]^2} $$.\nThis does not return an identity since $[m]\\neq [pc]$, so now we know where made a mistake, by just checking the units!\n\nTo calculate the value of the flux correctly, you need to convert the distance from parsecs to meters, because the flux should be written in units of [$W/m^2$]!\n\nThe correct answer is:\n\n```python\n# Correct version\nimport scipy\nfrom scipy.constants import pi, parsec\nL = 3.8275E26 # W\nr = 10*parsec #m\nF = L/(4*pi*r**2)\nprint(f'Solar luminosity: L = {L} W')\nprint(f'Distance: r = {r} pc')\nprint(f'Apparent brightness of the Sun at 10 parsec: F = L/(4*pi*r^2) = {F:1.4e} W/m/m')\n```\n\nSolar luminosity: L = 3.8275e+26 W\n\nDistance: r = 10 pc = 3.0857e+17 m\n\nApparent brightness of the Sun at 10 parsec: $F = \\frac{L}{4\\pi r^2} = 3.1989\\times 10^{-10} W/m^2$.\n</details>\n\n:::{.callout-caution collapse=\"false\"}\n## Sanity checks\nAlways be careful about the units used or units conversions!\n\nGet the habit of doing 'sanity checks': check the dimensional analysis and units when you use or derive formulas. This will help you spot some mistakes quickly and it is incredibly useful to rederive some formulas sometime.\n:::\nIn @eq-flux for instance, we know that the apparent brightness $F$ has units of [W/m $^2$] and that the luminosity $L$ has units of [W]. Writing the units of each side of the equation, we see that:\n$[W/m^2]=\\dfrac{[W]}{[m^2]}$, which as expected satisfies the identity, meaning that the formula is dimensionally correct.\n\n## Stellar magnitude scales\n\nThe flux from even nearby stars is tiny, but many bright stars are distinguished by the naked eye. The human eye (like hearing) responds logarithmically to stimulus. When comparing the flux densities of three stars in a 1:10:100 ratio, the perceived brightness gap between the first and second star appears to be the same as the difference between the second and third star. This equality in perceived brightness gaps illustrates that human perception of brightness operates on a logarithmic scale. Therefore, before modern photometry, astronomers had a scale based on their own naked-eye observations: __stellar (apparent) magnitude__.\n\n### Apparent magnitude\n\nThis system to measure the stars brightness was first introduced by the Greek astronomer Hipparchos, who compiled a catalog of 850 stars with their positions and their _apparent magnitudes_ on a scale from $m=1$, being the brightest stars, to $m=6$, being the faintest stars.\nThe apparent magnitude depends on the position of the observer the same way as the flux does (in fact, we will see in the following how these two quantities are related).\n\nThe image below shows an example of a star catalog created by ancient Greek astronomers.\n\n![_Almagest_ Ptolemy, c. 150AD image credit: Bibliothèque Nationale, Paris](img/Almagest.png){#fig-Almagest}\n\nThe English translation reads\n\n![Almagest translated](img/AlmagestTranslation.png){#fig-Almagest-translated}\n\nWe can still recognise the constellations and find these stars today!\n\n![<small>Ursa Minor constellation and magnitude scale. Image credit: By IAU and Sky &amp; Telescope magazine (Roger Sinnott &amp; Rick Fienberg) - <a rel=\"nofollow\" class=\"external autonumber\" href=\"http://www.iau.org/public/constellations/\">[1]</a>, <a href=\"https://creativecommons.org/licenses/by/3.0\" title=\"Creative Commons Attribution 3.0\">CC BY 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=15412502\">Link</a>\n</small>](img/littlebear.svg)\n\n\nThe modern names and magnitudes for these stars are reported in the table below.\n\n| Modern Name | Magnitude |\n|-------------|-----------|\n| Polaris | 1.98 |\n|Yildun | 4.35 |\n| $\\epsilon$ Umi | 4.21 |\n| Alasco | 4.95 |\n| Ahfa al Farkadain | 4.29 |\n| Pherkad | 3.04 |\n| Kochab | 2.07 |\n\n\n\nNote that some of the magnitudes of the little bear stars have changed since ancient times. Partly this is because the scientific definition and measurements are more precise, but also Polaris is a variable star (its brightness changes).\n\nThe apparent magnitude scale introduced by Hipparchos has been replaced by Pogson in 1856 and is no longer limited to values between 1 and 6, it now extends between m=-26.83 for the Sun to over m=30 for the faintest object, but the new classification kept these characteristics:\n\n- 5 magnitude steps correspond to a factor of 100 in apparent brightness\n- A difference of 1 magnitude corresponds to an apparent brightness ratio of $100^{1/5}\\simeq 2.512$, i.e. $$\\dfrac{F_{m+1}}{F_m}=100^{1/5}$${#eq-magnitude-flux-ratio}\n- Lower magnitudes are _brighter_\n- The zero point of the apparent magnitude has been _conventionally_ determined.\n\n<!-- This is not part of the S.I. system you are familiar with, but it is still widespread in astronomy today. We will learn how to use it in our calculations and relate it to S.I. units. -->\nThe _apparent magnitude_ $m$ is a measure of a star's apparent brightness, i.e. the flux received from the star, and it therefore depends on how close the star is to the observer.\n\nThe definition of the apparent magnitude is based on the difference between magnitudes and corresponds to the ratio between two stars' radiant fluxes, as stated in the properties above.\n\nIf we consider two stars with measured radiant fluxes (units $W/m^2$) $F_1$ and $F_2$, their apparent magnitudes will be related by\n$$\nm_1 - m_2 = -2.5 \\log_{10} \\frac{F_1}{F_2}\n$${#eq-apparent-magnitude}\n\n#### Apparent magnitude zero point convention\n\nThe values of the apparent magnitudes are determined in relation to a zero point value $m=0$. By convention, this corresponds to the observed flux $F_0$ below.\n\n::: {.callout-note appearance=\"minimalist\" icon=false}\n## Zero point flux (conventional)\n$$\nF_0 = 2.518 × 10^{−8} \\ \\mathrm{W m}^{−2}.\n$${#eq-zero-point-flux}\n(Reference: [IAU 2015 resolution](https://www.iau.org/static/resolutions/IAU2015_English.pdf))\n:::\n\nThe apparent magnitude of a star is therefore conventionally defined as\n\n::: {.callout-note style=\"simple\"}\n## Apparent magnitude (conventional)\n$$\nm = -2.5 \\log_{10}{\\frac{F}{F_0}} = -2.5 \\log_{10}{F} - 18.997\n$${#eq-apparent-magnitude-convention}\n:::\n\nThe apparent magnitude depends on the flux, and therefore on the intrinsic luminosity of the star and its distance ($r$) from Earth.\n\nUsing this zero point convention, from the _nominal solar flux_\n$$\nF_\\odot = 1361 \\mathrm{W/m}^2,\n$${#eq-sun-flux}\nwe can find that the apparent magnitude of the Sun is\n$$\nm_\\odot=-26.382\\ \\mathrm{mag}.\n$${#eq-sun-apparent-magnitude}\n\n### Magnitude and units\n\nNote that the magnitude is _dimensionless_, so it does not have units (check this quickly doing dimensional analysis: on the right hand side you have the logarithm of a number, no units). However, to remind us that a value (e.g. $m=-26$) is a magnitude, you can use the notation 'mag' after the numerical value (e.g. $m=-26$ mag).\n\n::: {.callouts-caution}\nBeware confusing mass and magnitude when using the same symbol $m$!\n:::\n\n### <span style=\"color:#336699;\">Question</span>\n\nThe coefficient in the formula for the apparent magnitude is 2.5. Why is it exactly 2.5 and _not_ $100^{1/5}\\simeq 2.512$?\n\n:::{.callout-tip collapse=true}\n## Hint\nUse the properties of logarithms.\n:::\n\n<details>\n<summary>Solution</summary>\nBased on the characteristics of the apparent magnitude listed above, for two stars with apparent magnitudes $m$ and $m+1$, the ratio between the fluxes is $$\n\\frac{F_{m+1}}{F_m}=100^{1/5}.$$\nHow can we rewrite this in a form that explicitely shows the difference between the magnitudes, $m-(m+1)$?\n\n\\begin{align}\n\\dfrac{F_{m+1}}{F_m}=100^{1/5} &\\implies \\log_{10}{\\dfrac{F_{m+1}}{F_m}}=\\log_{10}{10^{2/5}}=\\frac{2}{5}\\log_{10}{10}=\\frac{2}{5}\\\\ &\\implies \\frac{5}{2}\\log_{10}{\\dfrac{F_{m+1}}{F_m}} = 1 = (m+1) - m \\\\\n&\\implies m-(m+1)=-2.5\\log_{10}{\\dfrac{F_m}{F_{m+1}}}\n\\end{align}\n\nYou can see that the factor 2.5 comes from the ratio 5/2 in the derivation of the formula for the apparent magnitude (see the first passage).\n\n\n<!-- Note that the coefficient in the formula above for the apparent magnitude is 2.5 and _not_ 2.518! Why 2.5? Consider that the flux goes as $r^{-2}$, so $r\\propto F^{-1/2}$.\nPlug into the apparent magnitude formula and the $1/2$ divides the $5$ into $2.5$. -->\n\n<!-- ### Question\n\nShow that if we have two stars with measured fluxes (units $W/m^2$) $F_1$ and $F_2$, their magnitudes will be related by\n\n\\begin{align}\nm_1 - m_2 = -2.5 \\log_10_10_{10} \\frac{F_1}{F_2}\n\\end{align} -->\n\n<!-- __Hint:__\n\nUse the properties of logarithms.\n\n__Solution:__\n\nHaving defined the apparent magnitude using the zero point flux above, for the i-th star (i.e. for i=1,2) with flux $F_i$, the apparent magnitude is:\n$m_i = -2.5 \\log{\\dfrac{F_i}{F_0}}$\n\nTherefore:\n\\begin{align*}\nm_1 - m_2 & = -2.5 \\log{\\frac{F_1}{F_0}} - \\left(-2.5 \\log{\\frac{F_2}{F_0}}\\right) \\\\\n& = -2.5\\log F_1 - ( -2.5\\log F_0) - ( -2.5\\log F_2 - ( -2.5\\log F_0)) \\\\\n& = -2.5 \\log F_1 + 2.5 \\log F_2\\\\\n& = -2.5 \\log{\\frac{F_1}{F_2}}\n\\end{align*} -->\n\n### Absolute Magnitude\n\nAbsolute magnitude (M) is a measure solely of the star's intrinsic luminosity $L,$ so it does _not_ depend on its distance to the observer.\n\nIt is conventionally defined as the apparent magnitude of a star at a distance $r=10\\mathrm{pc}$.\n\nIf we consider two stars with luminosities $L_1$ and $L_2$, their absolute magnitudes will be related by\n\n$$\nM_1 - M_2 = -2.5\\log_{10}\\dfrac{L_1}{L_2}.\n$${#eq-absolute-magnitude}\n\n#### Absolute magnitude zero point convention\nTo define the zero point of the absolute magnitude ($M=0$), we use the same value of the zero flux, $F_0$ (@eq-zero-point-flux), used to define the apparent magnitude $m=0$, and we find the corresponding luminosity $L_0$ using @eq-flux for $r=10\\mathrm{pc}$.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\nfrom scipy.constants import pi, parsec\nf0 = 2.518021002E-8 # W/m/m\nr = 10*parsec # m\nL0 = 4*pi*r**2*f0 # W\nprint(f'r = 10 pc = {r:1.4e} m')\nprint(f'Conventional flux for zero apparent magnitude (m=0): F0={f0:1.4e} W/m/m')\nprint(f'Conventional luminosity for zero absolute magnitude (M=0): L0={L0:1.4e} W')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr = 10 pc = 3.0857e+17 m\nConventional flux for zero apparent magnitude (m=0): F0=2.5180e-08 W/m/m\nConventional luminosity for zero absolute magnitude (M=0): L0=3.0128e+28 W\n```\n:::\n:::\n\n\nThe zero value of the absolute magnitude, $M=0$, corresponds to a luminosity of\n\n::: {.callout-note appearance=\"minimalist\" icon=false}\n## Zero point luminosity (conventional)\n$$\nL_0 = 4\\pi r^2 F_0 = 3.0128 \\times 10^{28} \\mathrm{W}.\n$${#eq-zero-point-luminosity}\n(Reference: <a href=\"https://www.iau.org/static/resolutions/IAU2015_English.pdf\">IAU 2015 resolution.</a>)\n:::\n\nPlugging @eq-flux into @eq-apparent-magnitude-convention, and considering that by definition the absolute magnitude is equal to the apparent magnitude at a distance $r=10\\mathrm{pc}$, we can define the absolute magnitude as\n\n::: {.callout-note style=\"simple\"}\n## Absolute magnitude (conventional)\n$$\nM = -2.5 \\log_{10}{\\frac{L}{L_0}} = -2.5\\log_{10} L + 71.1974.\n$${#eq-absolute-mangitude-convention}\n:::\n\nUsing this convention, the absolute magnitude of the Sun, having a _nominal solar luminosity_ $L_\\odot = 3.828 \\times 10^{26} \\mathrm{W}$, is\n$$\nM_\\odot = 4.74\\mathrm{mag}.\n$${#eq-sun-absolute-magnitude}\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nfrom numpy import log10\nfrom astropy.constants import L_sun, L_bol0\n\nprint(L_sun)\nprint(L_bol0)\nL0 = 3.0128E28 # W\nM = -2.5*log10(L_sun/L_bol0)\nprint(f'Absolute magnitude of the Sun: M_sun = {M:.2f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Name   = Nominal solar luminosity\n  Value  = 3.828e+26\n  Uncertainty  = 0.0\n  Unit  = W\n  Reference = IAU 2015 Resolution B 3\n  Name   = Luminosity for absolute bolometric magnitude 0\n  Value  = 3.0128e+28\n  Uncertainty  = 0.0\n  Unit  = W\n  Reference = IAU 2015 Resolution B 2\nAbsolute magnitude of the Sun: M_sun = 4.74\n```\n:::\n:::\n\n\n:::{.callout-caution}\nIn different textbooks or sources (not updated to the IAU 2015 resolution), you may find different conventions for the zero points of apparent and absolute magnitudes. \nConsequently, you may have different values of the apparent and absolute magnitudes of the Sun (or other stars). For example, you may find that in some books the solar absolute bolometric magnitude is $M_\\odot=4.83$ instead of $M_\\odot=4.74$.\n:::\n\n### Setting the Absolute Magnitude scale\n\nWe will need to convert magnitudes to S.I. units of luminosity.\n<!-- __Updated convention__ -->\n\nBased on the <a link=\"https://www.iau.org/static/resolutions/IAU2015_English.pdf\"> IAU 2015 resolution</a>, we use the zero point luminosity previously introduced in @eq-zero-point-luminosity ($L_0=3.0128\\times 10^{28}$ W) to define the absolute magnitude in @eq-absolute-mangitude-convention.\nRearranging this, we find that for a star with absolute magnitude $M$, the luminosity is given by\n$$\nL = L_0 10^{-0.4 M}.\n$${#eq-absolute-magnitude-scale}\n\nYou may notice that this definition uses only the zero point value of the luminosity defined in @eq-zero-point-luminosity to relate the luminosity and absolute magnitude of a star.\n\n::: {.callout-caution}\nOnce again, some caution is needed when consulting textbooks and other sources, as conventions may change.\nOther (outdated) sources may use other references for the absolute magnitude $M_2$ of @eq-absolute-magnitude instead of the zero value used in @eq-absolute-mangitude-convention and in the derivation above. In some cases for instance you may find that the solar absolute magnitude is used: $M_2=M_{\\odot}=4.74$ (remember that even this value can change depending on the convention used, see 'caution' callout above.)\n:::\n\n\n\n<!-- __Outdated convention__ -->\n<!-- Some textbooks use the following (outdated) convention, illustrated here for completeness:\n- consider the absolute magnitude definition of @eq-absolute-magnitude and take the Sun as a reference, with absolute magnitude $M_2=M_{\\odot}=4.74$ (remember that even this value can change depending on the convention used, see 'caution' callout above. In the older convention $M_{\\odot}=4.83$.)\n- therefore, for a star with luminosity $L$ the absolute magnitude $M$ is given by\n$$\nM=-2.5\\log_{10}L+2.5\\log_{10}L_\\odot + 4.74.\n$${#eq-absolute-magnitude-scale-obsolete}\n- this can be rearranged to find the the luminosity of a star with absolute magnitude $M$:\n$$\nL=L_\\odot 10^{4.74 - M}.\n$$\nThis older convention uses the solar absolute magnitude as a reference. -->\n\n\n\n### <span style=\"color:#336699;\">Example</span>\n\nWe can use this formula to recover the luminosity of the Sun previously used ($L_\\odot = 3.826 \\times 10^{26}\\mathrm{W}$), having the absolute magnitude of the Sun, $M_\\odot = 4.74$.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nfrom astropy.constants import L_bol0\n\nM_sun = 4.74\nprint(L_bol0)\nL = L_bol0*10**(-0.4*M_sun)\nprint(f'Luminosity of the Sun: L = {L:1.3e}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Name   = Luminosity for absolute bolometric magnitude 0\n  Value  = 3.0128e+28\n  Uncertainty  = 0.0\n  Unit  = W\n  Reference = IAU 2015 Resolution B 2\nLuminosity of the Sun: L = 3.828e+26 W\n```\n:::\n:::\n\n\n### <span style=\"color:#336699;\">Question</span>\n\nShow that if we have two stars with luminosities (units $W$) $L_1$ and $L_2$ at the same distance $r=10\\mathrm{pc}$, their difference in the apparent magnitudes is the same as the difference of the absolute magnitudes:\n\n\\begin{align}\nM_1 - M_2 = -2.5 \\log_{10} \\frac{L_1}{L_2}\n\\end{align}\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\nUse the relationship between flux and luminosity and the properties of logarithms.\n:::\n\n<details>\n<summary>Solution</summary>\nFor two stars _at the same distance_ $r$ (e.g. two stars in a binary), we can write\n\\begin{align}\nm_1 - m_2 &= -2.5\\log_{10}\\left(\\frac{L_1}{4\\pi r^2} \\times \\frac{4\\pi r^2}{L_2} \\right)\\\\\n&= -2.5\\log_{10}\\frac{L_1}{L_2}\n\\end{align}\n\nHaving defined the absolute magnitude using the zero point flux above, for the i-th star (i.e. for i=1,2) with luminosities $L_i$ at distances of 10pc, the absolute magnitude is:\n$M_i = -2.5 \\log_{10}{\\dfrac{L_i}{L_0}}$\n\nTherefore:\n\\begin{align*}\nM_1 - M_2 & = -2.5 \\log_{10}{\\frac{L_1}{L_0}} - \\left(-2.5 \\log_{10}{\\frac{L_2}{L_0}}\\right) \\\\\n& = -2.5\\log_{10} L_1 +2.5\\log_{10} L_0 + 2.5\\log_{10} L_2 - 2.5\\log_{10} L_0 \\\\\n& = -2.5 \\log_{10} L_1 + 2.5 \\log_{10} L_2\\\\\n& = -2.5 \\log_{10}{\\frac{L_1}{L_2}}\n\\end{align*}\n\n- For two stars at the same distance of 10pc from the observer, the difference in the apparent magnitude is equal to the difference in the absolute magnitude.\n\n### Relationship between apparent magnitude and absolute magnitude\n\nBy using the conventional definitions of the apparent magnitude and absolute magnitude, we can find the relationship between them:\n\n\\begin{align}\nm &= -2.5\\log_{10}{\\frac{F}{F_0}} \\\\\n&= -2.5\\log_{10}\\left(\\frac{L}{4\\pi r^2}\\times \\frac{4\\pi (10\\mathrm{pc})^2}{L_0} \\right) \\\\\n& =-2.5\\log_{10}\\left(\\frac{L}{L_0}\\right) -2.5\\log_{10} \\left( \\frac{10\\mathrm{pc}}{r}\\right)^2\\\\\n& = M -5\\log_{10}(10\\mathrm{pc})+5\\log_{10}{r}\\\\\n& = M -5 + 5\\log_{10}{r}.\n\\end{align}\nThen\n$$\nM = m + 5 - 5\\log_{10} r.\n$${#eq-apparent-absolute-magnitude}\n\n:::{.callout-warning}\nCareful to the units in @eq-apparent-absolute-magnitude! Here $r$ is measured in __parsecs__. Use this formula with caution!\n:::\n\n\n<!-- ## 5.3. <a id='toc5_3_'></a>[Apparent magnitude and luminosity](#toc0_)\n\nIf the two objects are at the same distance $r$ (e.g. two stars in a binary) then we can write\n\n\\begin{align}\nm_1 - m_2 &= -2.5\\log_{10}\\left(\\frac{L_1}{4\\pi r^2} \\times \\frac{4\\pi r^2}{L_2} \\right)\\\\\n&= -2.5\\log_{10}\\frac{L_1}{L_2}\n\\end{align} -->\n\n<!-- ## 5.4. <a id='toc5_4_'></a>[Absolute magnitude and luminosity](#toc0_)\nRemember that the absolute magnitude $M$ is equal to the apparent magnitude $m$ at 10 pc distance.\n\nMathematically, using the relationship between apparent and absolute magnitudes: $M = m +5 -5\\log_{10}r$, it follows that\n\n\\begin{align}\nM_1 - M_2 = -2.5 \\log_{10}\\frac{L_1}{L_2}\n\\end{align} -->\n\n### Magnitudes, luminosity and distance\n\n- If you know a star's apparent magnitude $m$ and know its absolute magnitude $M$ you can calculate its distance $r$ (in parsec!) using $M=m + 5 - 5\\log_{10} r$.\n- If you know a star's apparent magnitude and distance you can compute its luminosity\n- You should practice this type of conversion!\n\n### <span style=\"color:#336699;\">Example</span>\n\nA star with apparent magnitude $4.2$ is measured by parallax to have a distance of $20$ parsecs. What is the absolute magnitude?\n\n::: {.cell slideshow='{\"slide_type\":\"notes\"}' execution_count=11}\n``` {.python .cell-code}\nfrom numpy import log10\nm=4.2\nr=20 #pc\nM = m + 5 - 5*log10(r)\nprint(f'M = m + 5 - 5*log10(r) = {m} + 5 - log10({r:.2f})={m}+5{-log10(r)} = {M}')\nprint(f'Absolute magnitude is {M:.2f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nM = m + 5 - 5*log10(r) = 4.2 + 5 - log10(20.00)=4.2+5-1.3010299956639813 = 2.694850021680093\nAbsolute magnitude is 2.69\n```\n:::\n:::\n\n\n## Notes on types of magnitude\n\nThe magnitude observed can depend on the sensitivity of the telescope or detector to the range of wavelengths. For instance, the human eye can observe in the visible part of the spectrum, but not in the IR or UV. Likewise, telescopes can have filters to observe different parts of the spectrum.\nMagnitude can therefore be specified for different wavelength intervals, i.e. observed with different coloured filters on the telescope.\n\n- For stars, the most commonly quoted magnitude is the **visual magnitude**, the magnitude in the visual part of the spectrum.\n- Another commonly used magnitude is the **bolometric magnitude**, which include the luminosity across the whole electromagnetic spectrum of wavelengths, whether observed or not. We will use this when performing some physics calculations.\n- One of the most common magnitude systems used in photometry is the **UBV system**, where magnitudes are measured through ultraviolet (U), blue (B) and visual (V) filters.\n\nThe magnitudes we mentioned so far, e.g. $M_\\odot = 4.74$, are __bolometric magnitudes__.\n\nThe visual magnitude $V$ and the bolometric magnitude $M_{bol}$ (or just $M$) are related by the _bolometric correction_ BC through the formula\n\n$$\nM_{bol} - V = BC,\n$${#eq-bolometric-correction}\n\nwhere $BC<0$.\n\nIn a multicolour system, such as UBV, it is useful to introduce the __colour index__. This is the difference between two magnitudes of that system.\nConsidering the UBV system, for instance:\n\n- the $U-B$ color index of a star is the difference between its ultraviolet and blue magnitudes ($U-B=M_U-M_B$)\n- the $B-V$ color index of a star is the difference between its blue and visual magnitudes ($V-B=M_V-M_B$).\n\nWe will come back to this again in the next chapter.\n\n# Recap\n\n- The distance to near stars can be determined using the parallax method\n- 1 parsec is the distance to a star having a parallax angle of 1 arcsec\n\n- The apparent brightness of a star scales with the inverse square of the distance to the star\n- The luminosity of a star is the total energy emitted per unit time \n\n- The magnitude scale is logarithmic\n- Apparent magnitude is a measure of brightness dependent on the distance to the observer\n- Absolute magnitude is a measure of brightness intrinsic to the star\n\n- We can find the luminosity in S.I. units from the absolute magnitude\n- We can convert apparent to absolute magnitude if we know the distance to the star in parsecs\n\n# Stellar Colour\n\n## Why are the stars different colours?\n![Stars of different colours](img/intro2.png)\n\nWe anticipated that stars have different colours in the first section of this chapter (see @fig-Stellarium-stars-compare), where we introduced the observed properties of stars.\n\nWhy are stars different colours?\n\nWe know that light is an electromagnetic wave, and that the colour we perceive depends on the wavelength of the light.\n\n![Linear representation of the visible light spectrum. Credits: [Wikimedia](https://upload.wikimedia.org/wikipedia/commons/d/d9/Linear_visible_spectrum.svg)](img/Linear_visible_spectrum.png){#fig-visible-spectrum}\n\n- Red light has a wavelength $\\approx 650$ nm\n- Blue light has a wavelength $\\approx 450$ nm\n- White light is a mixture of all visible wavelengths\n\nThe reason why stars appear to have different colours is that they do not emit the same amount of radiation at all wavelengths: some star emit more toward the red end of the spectrum, others toward the blue end, as well as beyond the visible window, such as emission in the infrared or ultraviolet.\n\nTo understand what regulates the emission of stars at the different wavelengths, determining the colours that we observe, we need to introduce the concept of _black-body_.\n\n\n## Black body radiation\n\n- A body that totally absorbs all radiation that falls upon it is called a __black-body__. You can think of it as a perfect absorber of radiation.\n- A black body is in thermal equilibrium, so it has a temperature $T$.\n- If it absorbs energy then it must also re-radiate it to stay in thermal equilibrium.\n- A black body is a perfect absorber but it is also a perfect emitter.\n\nWe anticipated that stars radiate different amounts of energy at different wavelengths. Let us assume that we can consider stars as black bodies.\n\nWhat is the distribution of radiation across wavelengths (or frequencies) that a black body emits?\n\n<!-- Earlier in this chapter we defined the _radiant flux_ (@eq-flux) as the energy received per second, per unit area. -->\n\nWe want to know the power emitted per unit wavelength $\\lambda$, per unit area, per unit solid angle (steradian): the __spectral radiance__ $B_\\lambda(\\lambda;T)$.\n\nFor a perfect emitter, radiation is emitted:\n\n- _equally_ from the surface of an object\n- _isotropically_ over solid angle.\n\n_The emission spectra of black bodies (the energy emitted against the wavelength or frequency) depend only on their temperature $T$._\n\nSo what is the form of the emission spectrum of a black body?\nAlthough the spectrum of black-body radiation was known observationally, its theoretical description has puzzled physicists at the end of the 19th Century and many attempts to describe this ran into trouble. It cannot be fully explained using classical physics, it requires quantum physics, as we will see in the following.\n\n### Rayleigh-Jeans law\n\nLord Rayleigh used classical physics to predict the shape of the black body spectrum, which was later refined by Sir James Jeans.\n\nThe Rayleigh-Jeans law is a good approximation to the observed spectrum at long wavelength (low frequencies) $hc\\ll k_BT\\lambda$.\n\n$$\nB_\\lambda^\\mathrm{RJ}(\\lambda; T) = \\frac{2ck_B T}{\\lambda^4}\n$${#eq-rayleigh-jeans-law}\n\n::: {layout-ncol=2}\n![Lord Rayleigh (1842 - 1918)](img/strutt.jpeg)\n\n![Sir James Jeans (1877 - 1946)](img/James_Hopwood_Jeans.jpg){height=80%}\n\n:::\n\n::: {.cell slideshow='{\"slide_type\":\"skip\"}' execution_count=12}\n``` {.python .cell-code}\nimport warnings\nwarnings.filterwarnings('ignore')\nimport numpy as np\nfrom astropy.constants import k_B, c, h\nfrom matplotlib import pyplot as plt\nfrom matplotlib import rc\nrc('text',usetex=True)\nrc('font',size=15)\nrc('figure',figsize=(8,6), dpi=300)\n\nl = np.linspace(0,3000,1000) # Wavelength, nm\nT = 4000 # Temperature, Kelvin\n\nB_rj=c.value* 2*k_B.value * T /(l*1e-9)**4; # 1e-9 to convert from nm to meters\n\nplt.plot(l, B_rj, label=\"Rayleigh-Jeans law\")\nplt.xlabel(r'Wavelength $\\lambda$ (nm)')\nplt.ylabel(r'Spectral Radiance $B_\\lambda(\\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)')\nplt.title('Spectral radiance')\nplt.ylim([0,1e15])\nplt.grid()\nplt.legend();\n```\n\n::: {.cell-output .cell-output-display}\n![Spectral radiance plotted using the Rayleigh-Jeans law (@eq-rayleigh-jeans-law).](SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-jeans-plot-output-1.png){#fig-rayleigh-jeans-plot}\n:::\n:::\n\n\nThe Rayleigh-Jeans law has a big problem - the radiance keeps increasing indefinitely at short wavelengths (higher frequencies). If it were true the power emitted at short wavelengths would be infinite! This is known as the _Ultraviolet Catastrophe_, and indicates the failure of classical physics to explain the behaviour of thermal radiation.\n\n### Wien's approximation\n\nWien's approximation, also referred to as Wien's law (not to be confused with 'Wien's displacement law'), is a good model for the observed spectrum at short wavelength (high frequencies) $hc\\gg k_BT\\lambda$, but it is not accurate at high wavelengths.\nWien's approximation is described by the form below.\n\n$$\nB_\\lambda^\\mathrm{Wien}(\\lambda; T) = \\frac{2 hc^2}{\\lambda^5}\\exp\\left(-\\frac{hc}{\\lambda k_B T}\\right)\n$${#eq-Wien_approx}\n\n::: {.cell slideshow='{\"slide_type\":\"skip\"}' execution_count=13}\n``` {.python .cell-code}\nB_wien=2 * h.value *c.value**2 * np.exp(-h.value*c.value/((l*1e-9)*k_B.value*T)) / (l*1e-9)**5;\n\nplt.plot(l, B_rj, label=\"Rayleigh-Jeans law\")\nplt.plot(l, B_wien, label=\"Wien's approximation\")\n\nplt.xlabel(r'Wavelength $\\lambda$ (nm)')\nplt.ylabel(r'Spectral Radiance $B_\\lambda(\\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)')\nplt.title('Spectral radiance')\nplt.ylim([0,5e12])\nplt.grid()\nplt.legend();\n```\n\n::: {.cell-output .cell-output-display}\n![Comparison of the spectral radiance plotted using the Rayleigh-Jeans law (@eq-rayleigh-jeans-law) and the Wien's approximation (@eq-Wien_approx).](SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-wien-plot-output-1.png){#fig-rayleigh-wien-plot}\n:::\n:::\n\n\n## Planck's Law\nIn 1900 Planck was able to derive a spectrum that fit the data by assuming that energy comes in discrete quanta of energy $E = h\\nu = hc/\\lambda$, with $h$ being a constant, Planck constant.\nThis marked the birth of quantum physics! The Planck radiation spectrum for a black body's spectral radiance is:\n\n$$\nB_\\lambda(\\lambda; T) = \\frac{2 hc^2}{\\lambda^5}\\left(\\frac{1}{\\exp\\left(\\frac{hc}{\\lambda k_B T}\\right) -1} \\right)\n$${#eq-planck-law}\n\n::: {.cell slideshow='{\"slide_type\":\"subslide\"}' execution_count=14}\n``` {.python .cell-code}\nB_planck = 2*h.value*c.value**2 * (1.0/(np.exp(h.value*c.value/(k_B.value*T*(l*1e-9)))-1)) / (l*1e-9)**5;\nplt.plot(l, B_planck, label=\"Planck's law\")\nplt.plot(l, B_wien, label=\"Wien's approximation\")\nplt.plot(l, B_rj, label=\"Rayleigh-Jeans law\")\n\nplt.xlabel(r'Wavelength $\\lambda$ (nm)')\nplt.ylabel(r'Spectral Radiance $B_\\lambda(\\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)')\nplt.title('Spectral radiance')\nplt.ylim([0,5e12])\nplt.grid()\nplt.legend();\n```\n\n::: {.cell-output .cell-output-display}\n![Comparison of the spectral radiance plotted using the Rayleigh-Jeans law (@eq-rayleigh-jeans-law), Wien's approximation (@eq-Wien_approx) and Planck's law (@eq-planck-law)](SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-wien-planck-plot-output-1.png){#fig-rayleigh-wien-planck-plot}\n:::\n:::\n\n\n### <span style=\"color:#336699;\">Exercise</span>\n\n1. Show that for low frequencies ($hc \\ll \\lambda k_B T$) the Rayleigh-Jeans law can be derived from the Planck law.\n1. Show that for high frequencies ($hc \\gg \\lambda k_B T$) Wien's law can be derived from the Planck law.\n\n:::{.callout-tip collapse=true}\n## Hint\nYou can use the approximation $\\lim_{x\\rightarrow  0} \\exp(x) = 1 + x$\n:::\n\n# Temperature and colour\n\nLet's look at how the spectrum changes with temperature $T$.\n\nWe can try out this [PhET interactive simulator](https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum_en.html) and by varying the temperature we can see how the black body spectrum changes.\n\nThe change of the spectral radiance with temperature is shown in @fig-spectral-radiance-vs-temp.\n\n::: {.cell slideshow='{\"slide_type\":\"subslide\"}' execution_count=15}\n``` {.python .cell-code}\nimport warnings\nwarnings.filterwarnings('ignore')\nimport matplotlib.pyplot as plt\n\nfor T in [6000,5500,5000,4500,4000]:\n    B_planck = 2*h.value*c.value**2 * (1.0/(np.exp(h.value*c.value/(k_B.value*T*(l*1e-9)))-1)) / (l*1e-9)**5\n    plt.plot(l, B_planck, label='T='+str(T)+'K')\n\n\nplt.xlabel(r'Wavelength $\\lambda$ (nm)')\nplt.ylabel(r'Spectral Radiance $B_\\lambda(\\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)')\nplt.title('Spectral radiance at different temperatures')\nplt.grid()\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Spectral radiance at different temperatures.](SP1.1_-_Stellar_Properties_files/figure-html/fig-spectral-radiance-vs-temp-output-1.png){#fig-spectral-radiance-vs-temp}\n:::\n:::\n\n\nFrom @fig-spectral-radiance-vs-temp we notice that the Planck spectrum:\n\n- has a clear peak at some wavelength, which decreases as temperature increases\n- $B_\\lambda(\\lambda;T)> 0$ for all wavelengths, but tends toward $0$ at the extreme ends of the spectrum\n- overall increases with temperature\n\n\nBlack bodies radiate at all wavelengths - they won't look black! The shape of the spectrum and the position of the peak determine the apparent colour of the object.\n\n## Wien's displacement law\n\nThere is an inverse relationship between the temperature $T$ in Kelvin and the peak emission wavelength $\\lambda_{peak}$ in metres, called _Wien's displacement law_:\n$$\n\\lambda_{peak} = \\frac{0.0029\\,\\mathrm{m\\,K}}{T}\n$${#eq-wien-displacement-law}\n\nHere $\\mathrm{m\\,K}$ are metres $\\times$ kelvin, the units of the constant.\n\nNote that this is different from Wien's law, or Wien's approximation, encountered earlier (@eq-Wien_approx).\n\nWe can use Wien's displacement law to determine the effective temperature of a star from the spectrum of its light, assuming it is a black body.\n\n### <span style=\"color:#336699;\">Question</span>\n\nThe Sun's spectrum has a peak wavelength of around 500 nm, in the green part of the spectrum (see @fig-solar-irradiance).\nWhat is the effective emission temperature of the Sun?\n\n![Spectrum of Solar Radiation as seen from Earth and from above Earth's atmosphere, and fitting of the black-body curve.](img/solar_irradiance.png){#fig-solar-irradiance}\n\n<details>\n<summary>Solution</summary>\nWe can use @eq-wien-displacement-law, after converting the peak wavelength from nm to m.\n\n::: {.cell slideshow='{\"slide_type\":\"notes\"}' execution_count=16}\n``` {.python .cell-code}\nw = 0.0029 # constant in m K\nlmax = 500e-9 # peak wavelength in metres\nTsun = w/lmax\nprint(f'The effective temperature of the Sun is approximately {Tsun:.3f} K')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe effective temperature of the Sun is approximately 5800.000 K\n```\n:::\n:::\n\n\nThe commonly used value for the emission temperature of the Sun is $T_\\odot=5780$ K.\nAlthough the peak emission is greenish, the distribution overall produces light that appears yellowish to us, after passing through the atmosphere.\n\n</details>\n\n## Converting between wavelength and frequency\n\nSo far we have been using the spectral radiance in terms of wavelength $B_\\lambda(\\lambda;T).$ It can also be expressed in terms of the frequency of the radiation $B_\\nu(\\nu;T)$. Since it is a density across wavelengths, we must be careful when converting between them.\n\n\\begin{align}\nB_\\nu(\\nu;T)d\\nu &= B_\\lambda(\\lambda;T)d\\lambda \\\\\nB_\\nu(\\nu;T) &= B_\\lambda(\\lambda(\\nu);T) \\left|\\frac{d\\lambda}{d\\nu}\\right| \\\\\n &= B_\\lambda(c/\\nu; T) \\left|-\\frac{c}{\\nu^2}\\right| \\\\\n  &= \\frac{2h\\nu^5}{c^3}\\left( \\frac{1}{\\exp\\left(\\frac{h\\nu}{k_BT}\\right)-1} \\right) \\times \\frac{c}{\\nu^2}\n\\end{align}\n$$\n  B_\\nu(\\nu;T) = \\frac{2h\\nu^3}{c^2}\\left( \\frac{1}{\\exp\\left(\\frac{h\\nu}{k_BT}\\right)-1}\\right)\n$${#eq-wavelength-frequency-conversion}\n\n:::{.callout-warning}\n## Warning\nIn the conversion derived above, we do not simply do a change of variable using the relationship between frequency and wavelength $\\nu = \\frac{c}{\\lambda}$! In the conversion from $B_{\\lambda}$ to $B_{\\nu}$ there is a factor\n$$\n\\left|\\frac{d\\lambda}{d\\nu}\\right|=\\frac{c}{\\nu^2}.\n$$\n\nThis is due to the fact that\n$$\n\\Delta\\nu = \\nu_2-\\nu_1 = \\frac{c}{\\lambda_2}-\\frac{c}{\\lambda_1} \\neq \\frac{c}{\\Delta\\lambda},\n$$\nwhich applies also to the infinitesimal case! Therefore we need to consider the derivative $\\frac{d\\lambda}{d\\nu}$.\n:::\n\n## Are stars really black bodies?\nLet's take a look at the example of the Solar spectrum of @fig-solar-irradiance.\n\n- The Planck black body spectrum is a theoretical prediction for an ideal case, which does not perfectly match the observed one with all its features, but it is usually a good fit.\n- Light from the Sun is obscured by the atmosphere of the Earth, which absorbs some wavelengths more than others. This is called _atmospheric extinction_. We will ignore this effect in this course.\n- There are also _spectral lines_, gaps in the solar spectrum. More on this later.\n\n# Stefan-Boltzmann Law\n\nThe __total (bolometric) luminosity per area__ (\"radiant emittance\" $j=\\frac{L}{A}$) has units of $\\mathrm{W\\,m}^{-2}$, and is the spectral radiance integrated over solid angle and wavelength:\n\nThe equation for this is known as the Stefan-Boltzmann Law.\n$$\nj = \\frac{\\pi^2 k_B^4 T^4}{60 \\hbar^3 c^2}.\n$${#eq-stefan-boltzmann-law}\n\nThis can be written more simply as\n\n$$\nj = \\sigma T^4\n$${#eq-stefan-boltzmann-law-sigma}\n\nwhere \n$$\n\\sigma = \\frac{\\pi^2 k_B^4 }{60 \\hbar^3 c^2} = 5.67\\times 10^{-8}\\mathrm{W\\,m^{-2}K^{-4}} \n$${#eq-stefan-boltzmann-const}\nis the Stefan-Boltzmann constant.\n\n# Stellar luminosity\n\nWe can multiply @eq-stefan-boltzmann-const by the surface area to find the total luminosity of a spherical star of radius $R$.\n\n::: {.callout-note appearance=\"simple\"}\n## Total bolometric luminosity\n$$\nL = 4\\pi R^2 \\sigma T^4\n$${#eq-total-luminosity}\nThis is the most useful form to use in stellar calculations - __remember it__!\n:::\n\n\nIt allows us to relate $R$, $L$, and $T$ for a star.\n\n- If we know the apparent magnitude and the distance $d$, then we can find the absolute magnitude using @eq-apparent-absolute-magnitude.\n- If we know the absolute magnitude we can find the luminosity using @eq-absolute-magnitude-scale\n- If we know the luminosity and the temperature we can find the star's radius using @eq-total-luminosity!\n\nYou need to be able to solve these types of problem - __practice it__!\n\n### <span style=\"color:#336699;\">Example</span>\n\n$\\epsilon$-Eridani is a star at $r=3.212$ parsecs distance, with an apparent bolometric magnitude of 3.54 and a peak emission wavelength of 570 nm.\nWhat else can we tell about it? Which other quantities can we derive?\n\n- __Absolute bolometric magnitude__\n\nKnowing the apparent bolometric magnitude $m_\\epsilon$ and the distance $r$:\n\n\\begin{align}\nM_\\epsilon &= m_\\epsilon + 5 - 5\\log_{10}r \\\\\n  &= 3.54 + 5 - 5\\log_{10}(3.2) \\\\\n  &= 6.0\n\\end{align}\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\nfrom numpy import log10\nm = 3.54\nr = 3.212 #pc\nM = m + 5 - 5*log10(r)\nprint(f'Absolute magnitude: {M:.1f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAbsolute magnitude: 6.0\n```\n:::\n:::\n\n\n- __Luminosity__\n\nKnowing the absolute bolometric magnitude $M_\\epsilon$ and the zero point luminosity $L_0$ defined in @eq-zero-point-luminosity, we can use @eq-absolute-magnitude-scale\n$$\nL\\epsilon = L_0 10^{-0.4 M_\\epsilon}\n= 3.0128 \\times 10^{28} \\times 10^{-0.4 \\times 6.0}\n= 1.2\\times 10^{26} \\mathrm{W}\n$$\n\n::: {.cell execution_count=18}\n``` {.python .cell-code}\nL0 = 3.0128E28\nL = L0*10**(-0.4*M)\nprint(f'Bolometric luminosity {L:.3e}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBolometric luminosity 1.193e+26\n```\n:::\n:::\n\n\n- __Temperature__\n\nUsing Wien's displacement law (@eq-wien-displacement-law):\n\n$$\n\\lambda_{peak} T_\\epsilon = 0.0029 \\implies\nT_\\epsilon = \\frac{0.0029}{ 570\\times 10^{-9}} = T_\\epsilon = 5088\\,\\mathrm{K}\n$$\n\n::: {.cell execution_count=19}\n``` {.python .cell-code}\nc = 0.0029 # m K\nwavel = 570E-9 # m \nT = c/wavel\nprint(f'Temperature: T={T:.3e}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTemperature: T=5.088e+03\n```\n:::\n:::\n\n\n- __Radius__\n\nRearranging @eq-total-luminosity:\n$$\nR_\\epsilon = \\sqrt{\\frac{L_\\epsilon}{4\\pi \\sigma T^4}}\n= \\sqrt{\\frac{1.3\\times 10^{26}}{4\\pi \\times 5.671\\times10^{-8}\\times 5088^4}} = 5.00\\times 10^{8}\\,\\mathrm{m}\n$$\n\n::: {.cell execution_count=20}\n``` {.python .cell-code}\nfrom numpy import sqrt, pi\nsigma = 5.671E-8\nR = sqrt(L/(4*pi*sigma*T**4))\nprint(f'Radius: R={R:.3e}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRadius: R=4.998e+08\n```\n:::\n:::\n\n\n# Recap\n\n- Black bodies are perfect absorbers and emitters that absorb and emit at all wavelengths\n- __Planck radiation law__ gives the shape of the black-body emission spectrum\n- __Wien's displacement law__ relates the peak emission wavelength to the temperature\n- __Stefan-Boltzmann law__ can be used to find the total power radiated by a black body\n\n",
    "supporting": [
      "SP1.1_-_Stellar_Properties_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}