<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr Rosaria Lena">
<meta name="dcterms.date" content="2026-01-11">
<meta name="description" content="Lectures 1-3 (part 1.1).">

<title>Stellar Physics - 1&nbsp; Stellar properties</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./SP1.2_-_Stellar_classification.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./SP1.1_-_Stellar_Properties.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Stellar properties</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Stellar properties</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
                  <div>
        <div class="description">
          <em>Lectures 1-3</em> (part 1.1).
        </div>
      </div>
                </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">email</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Dr Rosaria Lena </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              rosaria.lena@glasgow.ac.uk
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 11, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stellar Physics</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Stellar-Physics.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Stellar-Physics.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.1_-_Stellar_Properties.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Stellar properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.2_-_Stellar_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Classifying stars</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.3_-_Variables_and_Binaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variables and binaries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.4_-_Stellar_Atmospheres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stellar Atmospheres</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.5_-_Stellar_Models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Stellar Models and Evolution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP1.6_-_Post-Main-Sequence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Post-main-sequence Evolution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP2.1_-_Supernovae.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Supernovae</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP2.2_-_Degenerate_Matter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Degenerate Matter and Degeneracy Pressure</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP2.3_-_White_Dwarfs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">White Dwarfs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP2.4_-_Neutron_Stars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Neutron Stars</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SP2.5_-_Black_Holes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Black Holes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#look-at-the-night-sky-what-do-we-see" id="toc-look-at-the-night-sky-what-do-we-see" class="nav-link active" data-scroll-target="#look-at-the-night-sky-what-do-we-see"><span class="header-section-number">1.1</span> Look at the night sky, what do we see?</a></li>
  <li><a href="#what-is-a-star" id="toc-what-is-a-star" class="nav-link" data-scroll-target="#what-is-a-star"><span class="header-section-number">1.2</span> What is a star?</a>
  <ul class="collapse">
  <li><a href="#life-and-death-of-a-star" id="toc-life-and-death-of-a-star" class="nav-link" data-scroll-target="#life-and-death-of-a-star"><span class="header-section-number">1.2.1</span> Life and death of a star</a></li>
  <li><a href="#do-all-stars-look-the-same" id="toc-do-all-stars-look-the-same" class="nav-link" data-scroll-target="#do-all-stars-look-the-same"><span class="header-section-number">1.2.2</span> Do all stars look the same?</a></li>
  <li><a href="#a-comparison-between-two-stars-on-stellarium" id="toc-a-comparison-between-two-stars-on-stellarium" class="nav-link" data-scroll-target="#a-comparison-between-two-stars-on-stellarium"><span class="header-section-number">1.2.3</span> A comparison between two stars on Stellarium</a></li>
  <li><a href="#what-can-we-tell-from-observations" id="toc-what-can-we-tell-from-observations" class="nav-link" data-scroll-target="#what-can-we-tell-from-observations"><span class="header-section-number">1.2.4</span> What can we tell from observations?</a></li>
  </ul></li>
  <li><a href="#how-distant-are-the-stars" id="toc-how-distant-are-the-stars" class="nav-link" data-scroll-target="#how-distant-are-the-stars"><span class="header-section-number">1.3</span> How distant are the stars?</a>
  <ul class="collapse">
  <li><a href="#an-easy-case-the-distance-to-the-sun" id="toc-an-easy-case-the-distance-to-the-sun" class="nav-link" data-scroll-target="#an-easy-case-the-distance-to-the-sun"><span class="header-section-number">1.3.1</span> An easy case: the distance to the Sun</a></li>
  <li><a href="#the-astronomical-unit" id="toc-the-astronomical-unit" class="nav-link" data-scroll-target="#the-astronomical-unit"><span class="header-section-number">1.3.2</span> The astronomical unit</a></li>
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question"><span class="header-section-number">1.3.3</span> <span style="color:#336699;">Question</span></a></li>
  <li><a href="#size-of-our-solar-system" id="toc-size-of-our-solar-system" class="nav-link" data-scroll-target="#size-of-our-solar-system"><span class="header-section-number">1.3.4</span> Size of our solar system</a></li>
  <li><a href="#measuring-the-distance-to-the-stars" id="toc-measuring-the-distance-to-the-stars" class="nav-link" data-scroll-target="#measuring-the-distance-to-the-stars"><span class="header-section-number">1.3.5</span> Measuring the distance to the stars</a></li>
  <li><a href="#transit-method" id="toc-transit-method" class="nav-link" data-scroll-target="#transit-method"><span class="header-section-number">1.3.6</span> Transit method</a></li>
  </ul></li>
  <li><a href="#how-big-are-stars" id="toc-how-big-are-stars" class="nav-link" data-scroll-target="#how-big-are-stars"><span class="header-section-number">1.4</span> How big are stars?</a>
  <ul class="collapse">
  <li><a href="#how-big-is-the-sun" id="toc-how-big-is-the-sun" class="nav-link" data-scroll-target="#how-big-is-the-sun"><span class="header-section-number">1.4.1</span> How big is the Sun?</a></li>
  <li><a href="#what-about-other-stars" id="toc-what-about-other-stars" class="nav-link" data-scroll-target="#what-about-other-stars"><span class="header-section-number">1.4.2</span> What about other stars?</a></li>
  <li><a href="#a-handy-guide-to-estimating-angular-diameters" id="toc-a-handy-guide-to-estimating-angular-diameters" class="nav-link" data-scroll-target="#a-handy-guide-to-estimating-angular-diameters"><span class="header-section-number">1.4.3</span> A <em>handy</em> guide to estimating angular diameters</a></li>
  <li><a href="#how-far-apart-are-the-stars" id="toc-how-far-apart-are-the-stars" class="nav-link" data-scroll-target="#how-far-apart-are-the-stars"><span class="header-section-number">1.4.4</span> How far apart are the stars?</a></li>
  </ul></li>
  <li><a href="#how-bright-are-stars" id="toc-how-bright-are-stars" class="nav-link" data-scroll-target="#how-bright-are-stars"><span class="header-section-number">1.5</span> How bright are stars?</a>
  <ul class="collapse">
  <li><a href="#apparent-brightness-and-luminosity" id="toc-apparent-brightness-and-luminosity" class="nav-link" data-scroll-target="#apparent-brightness-and-luminosity"><span class="header-section-number">1.5.1</span> Apparent brightness and luminosity</a></li>
  <li><a href="#apparent-magnitude" id="toc-apparent-magnitude" class="nav-link" data-scroll-target="#apparent-magnitude"><span class="header-section-number">1.5.2</span> Apparent magnitude</a></li>
  <li><a href="#magnitude-and-units" id="toc-magnitude-and-units" class="nav-link" data-scroll-target="#magnitude-and-units"><span class="header-section-number">1.5.3</span> Magnitude and units</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">1.5.4</span> <span style="color:#336699;">Question</span></a></li>
  <li><a href="#absolute-magnitude" id="toc-absolute-magnitude" class="nav-link" data-scroll-target="#absolute-magnitude"><span class="header-section-number">1.5.5</span> Absolute Magnitude</a></li>
  <li><a href="#setting-the-absolute-magnitude-scale" id="toc-setting-the-absolute-magnitude-scale" class="nav-link" data-scroll-target="#setting-the-absolute-magnitude-scale"><span class="header-section-number">1.5.6</span> Setting the Absolute Magnitude scale</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">1.5.7</span> <span style="color:#336699;">Example</span></a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">1.5.8</span> <span style="color:#336699;">Question</span></a></li>
  <li><a href="#relationship-between-apparent-magnitude-and-absolute-magnitude" id="toc-relationship-between-apparent-magnitude-and-absolute-magnitude" class="nav-link" data-scroll-target="#relationship-between-apparent-magnitude-and-absolute-magnitude"><span class="header-section-number">1.5.9</span> Relationship between apparent magnitude and absolute magnitude</a></li>
  <li><a href="#magnitudes-luminosity-and-distance" id="toc-magnitudes-luminosity-and-distance" class="nav-link" data-scroll-target="#magnitudes-luminosity-and-distance"><span class="header-section-number">1.5.10</span> Magnitudes, luminosity and distance</a></li>
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span class="header-section-number">1.5.11</span> <span style="color:#336699;">Example</span></a></li>
  <li><a href="#notes-on-types-of-magnitude" id="toc-notes-on-types-of-magnitude" class="nav-link" data-scroll-target="#notes-on-types-of-magnitude"><span class="header-section-number">1.5.12</span> Notes on types of magnitude</a></li>
  </ul></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">1.6</span> Recap</a></li>
  <li><a href="#stellar-colour" id="toc-stellar-colour" class="nav-link" data-scroll-target="#stellar-colour"><span class="header-section-number">1.7</span> Stellar Colour</a>
  <ul class="collapse">
  <li><a href="#why-are-the-stars-different-colours" id="toc-why-are-the-stars-different-colours" class="nav-link" data-scroll-target="#why-are-the-stars-different-colours"><span class="header-section-number">1.7.1</span> Why are the stars different colours?</a></li>
  <li><a href="#black-body-radiation" id="toc-black-body-radiation" class="nav-link" data-scroll-target="#black-body-radiation"><span class="header-section-number">1.7.2</span> Black body radiation</a></li>
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span class="header-section-number">1.7.3</span> <span style="color:#336699;">Exercise</span></a></li>
  </ul></li>
  <li><a href="#temperature-and-colour" id="toc-temperature-and-colour" class="nav-link" data-scroll-target="#temperature-and-colour"><span class="header-section-number">1.8</span> Temperature and colour</a>
  <ul class="collapse">
  <li><a href="#wiens-displacement-law" id="toc-wiens-displacement-law" class="nav-link" data-scroll-target="#wiens-displacement-law"><span class="header-section-number">1.8.1</span> Wien’s displacement law</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><span class="header-section-number">1.8.2</span> <span style="color:#336699;">Question</span></a></li>
  <li><a href="#converting-between-wavelength-and-frequency" id="toc-converting-between-wavelength-and-frequency" class="nav-link" data-scroll-target="#converting-between-wavelength-and-frequency"><span class="header-section-number">1.8.3</span> Converting between wavelength and frequency</a></li>
  <li><a href="#are-stars-really-black-bodies" id="toc-are-stars-really-black-bodies" class="nav-link" data-scroll-target="#are-stars-really-black-bodies"><span class="header-section-number">1.8.4</span> Are stars really black bodies?</a></li>
  <li><a href="#stefan-boltzmann-law" id="toc-stefan-boltzmann-law" class="nav-link" data-scroll-target="#stefan-boltzmann-law"><span class="header-section-number">1.8.5</span> Stefan-Boltzmann Law</a></li>
  </ul></li>
  <li><a href="#stellar-luminosity" id="toc-stellar-luminosity" class="nav-link" data-scroll-target="#stellar-luminosity"><span class="header-section-number">1.9</span> Stellar luminosity</a>
  <ul class="collapse">
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2"><span class="header-section-number">1.9.1</span> <span style="color:#336699;">Example</span></a></li>
  </ul></li>
  <li><a href="#recap-1" id="toc-recap-1" class="nav-link" data-scroll-target="#recap-1"><span class="header-section-number">1.10</span> Recap</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<hr>
<section id="look-at-the-night-sky-what-do-we-see" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="look-at-the-night-sky-what-do-we-see"><span class="header-section-number">1.1</span> Look at the night sky, what do we see?</h2>
<p>Let’s start with some simple observations of the night sky…</p>
<p>“Look at the night sky, what do we see?”</p>
<p>Here in Scotland, the answer to this questions is likely ‘clouds’, but if you are curious to know what is beyond those clouds, you can check out Stellarium (you can download it or you can use the <a href="https://stellarium-web.org/">web version</a>).</p>
<p>All that glitters is not (only) stars!</p>
<div id="fig-Stellarium" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Stellarium_full.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.1: An example of the night sky view taken from Stellarium</figcaption>
</figure>
</div>
<p>Looking at the night sky we may be able to see planets, meteors, galaxies, satellites, comets, star clusters and many stars!</p>
<div id="fig-Stellarium-marked" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Stellarium_full_description.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.2: An example of the night sky view taken from Stellarium (with marked typical objects)</figcaption>
</figure>
</div>
</section>
<section id="what-is-a-star" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="what-is-a-star"><span class="header-section-number">1.2</span> What is a star?</h2>
<p>A star is an astronomical spheroid body:</p>
<ul>
<li>held together by <em>self-gravity</em></li>
<li><em>radiating</em> energy from an internal source (tipycally from nuclear fusion reactions, and occasionally from the release of gravitational potential energy during contraction or collapse)</li>
</ul>
<p>Having this definition you should be able to answer the following questions:</p>
<ol type="1">
<li>Is the Death Star a (fictional) star?</li>
</ol>
<details>
<summary>
Answer
</summary>
The answer is “no”, because it does not radiate energy! The Death Star is actually a (fictional) space station orbiting the (fictional) planet moon of Endor. Enough with the fictional stuff now.
</details>
<ol start="2" type="1">
<li>If you look at the sky you may see that planets and comets are also shining in the sky, so why can’t they be considered stars, based on the definition given above? Do they radiate energy? Are they self-gravitating?</li>
</ol>
<details>
<summary>
Answer
</summary>
Planets actually do not <em>radiate</em>, they mostly reflect the light coming from the Sun, and the same holds for comets. In addition to that, comets do not have enough mass to be considered self-gravitating objects.
</details>
<section id="life-and-death-of-a-star" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="life-and-death-of-a-star"><span class="header-section-number">1.2.1</span> Life and death of a star</h3>
<p>A star is not a static object. During its life it will evolve, changing its internal structure and chemical composition as it ‘burns its <em>fuel</em>’ and changing its mass and size.</p>
<p>The death of a star eventually occurs when one of the conditions that define a star is no longer valid, i.e.&nbsp;when the star is no longer self-gravitating, or when it stops radiating having exhausted its nuclear fuel.</p>
<p>We will talk more about the evolution of stars in the following lectures. Now let’s go back to what we can observe having a look at the night sky and let’s see what we can tell from observations of stars.</p>
</section>
<section id="do-all-stars-look-the-same" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="do-all-stars-look-the-same"><span class="header-section-number">1.2.2</span> Do all stars look the same?</h3>
<p><img src="img/intro2.png" width="600" height="600"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/M3_color3.gif" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Examples of stars</figcaption>
</figure>
</div>
<ul>
<li>There are a lot of stars, not uniformly distributed</li>
<li>Some look brighter than others</li>
<li>Some are bigger than others</li>
<li>They have different colours</li>
<li>Sometimes there are coloured or dark areas around stars</li>
<li>Some stars have fluctuating brightness: repeating and irregular</li>
</ul>
</section>
<section id="a-comparison-between-two-stars-on-stellarium" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="a-comparison-between-two-stars-on-stellarium"><span class="header-section-number">1.2.3</span> A comparison between two stars on Stellarium</h3>
<p>Let’s check the properties of two stars on Stellarium. What can you notice after a first look at these stars in <a href="#fig-Stellarium-stars-compare">Figure&nbsp;<span>1.3</span></a>? You may notice that they have different colours (one looks white, the other one looks white-blue). The boxes contain some information about these stars, and you may recognise many of these fields in the blue boxes from positional astronomy. We will find out what the properties in the red boxes mean during this course.</p>
<div id="fig-Stellarium-stars-compare" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Stellarium_stars_p.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.3: Comparison between two stars on Stellarium</figcaption>
</figure>
</div>
</section>
<section id="what-can-we-tell-from-observations" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="what-can-we-tell-from-observations"><span class="header-section-number">1.2.4</span> What can we tell from observations?</h3>
<ul>
<li>How distant are the stars?</li>
<li>How big are they?</li>
<li>How bright?</li>
<li>How, when and where do they form?</li>
<li>What are their most important characteristics?</li>
<li>What are they made of?</li>
<li>What is their energy source?</li>
<li>What happens when it runs out?</li>
</ul>
</section>
</section>
<section id="how-distant-are-the-stars" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="how-distant-are-the-stars"><span class="header-section-number">1.3</span> How distant are the stars?</h2>
<section id="an-easy-case-the-distance-to-the-sun" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="an-easy-case-the-distance-to-the-sun"><span class="header-section-number">1.3.1</span> An easy case: the distance to the Sun</h3>
<p><strong>How do we find the distance to the Sun?</strong></p>
<p>Easy! - Just define The Astronomical Unit (a.u.) as the average distance between the Earth and the Sun!</p>
</section>
<section id="the-astronomical-unit" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="the-astronomical-unit"><span class="header-section-number">1.3.2</span> The astronomical unit</h3>
<p>Ok, but how big is an au? In 1976 the International Astronomical Union (IAU) adopted a standard definition whose value has been updated with increasing precision during the years. At the current date, the astronomical unit has the following value.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Astronomical unit value
</div>
</div>
<div class="callout-body-container callout-body">
<p>1 a.u. = 149,597,870,700 m</p>
</div>
</div>
</section>
<section id="question" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="question"><span class="header-section-number">1.3.3</span> <span style="color:#336699;">Question</span></h3>
<p>Can you now work out how long it takes for the sunlight to reach Earth?</p>
<details>
<summary>
Solution
</summary>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;fragment&quot;}" data-execution_count="1">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> math</span>
<span id="cb1-2"><a href="#cb1-2"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>c <span class="op">=</span> <span class="fl">299792.458</span> <span class="co"># km/s</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>ts <span class="op">=</span> AU<span class="op">/</span>c <span class="co"># s</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>tm <span class="op">=</span> ts<span class="op">/</span><span class="dv">60</span> <span class="co"># min</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="bu">print</span>(<span class="ss">f"Time taken by light to reach Earth from the Sun = </span><span class="sc">{</span>ts<span class="sc">:1.4}</span><span class="ss"> s = </span><span class="sc">{</span>tm<span class="sc">:1.4}</span><span class="ss"> min = 8 min 19 s "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Time taken by light to reach Earth from the Sun = 499.0 s = 8.317 min = 8 min 19 s </code></pre>
</div>
</div>
</details>
<section id="a-remark-on-the-astronomical-unit" class="level4" data-number="1.3.3.1">
<h4 data-number="1.3.3.1" class="anchored" data-anchor-id="a-remark-on-the-astronomical-unit"><span class="header-section-number">1.3.3.1</span> A remark on the Astronomical Unit</h4>
<p>Note: 1 a.u. is an <em>average</em> distance, because the distance between the Earth and the Sun varies during the year.</p>
<div id="fig-perhelion-aphelion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Earth-orbit-Sun_fixed.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.4: Illustration of the perhelion and aphelion in Earth’s orbit around the Sun</figcaption>
</figure>
</div>
<!-- <div>
<img src="img/Earth-orbit-Sun_fixed.png" width="700" height="500"/>
</div> -->
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;fragment&quot;}" data-execution_count="2">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="im">import</span> math</span>
<span id="cb3-2"><a href="#cb3-2"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>aphD <span class="op">=</span> <span class="dv">152100000</span> <span class="co"># km</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>perD <span class="op">=</span> <span class="dv">147100000</span> <span class="co"># km</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>AU_avg <span class="op">=</span> (aphD<span class="op">+</span>perD)<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>AU) <span class="co">#&nbsp;Average distance, gives AU, check: print(f"{AU_avg}")</span></span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="bu">print</span>(<span class="ss">f"Distance Earth-Sun at aphelion (most distant) = </span><span class="sc">{</span>aphD<span class="sc">:1.3e}</span><span class="ss"> km = </span><span class="sc">{</span>aphD<span class="op">/</span>AU<span class="sc">:1.4}</span><span class="ss"> au"</span>)</span>
<span id="cb3-7"><a href="#cb3-7"></a><span class="bu">print</span>(<span class="ss">f"Distance Earth-Sun at perihelion (closest) = </span><span class="sc">{</span>perD<span class="sc">:1.3e}</span><span class="ss"> km = </span><span class="sc">{</span>perD<span class="op">/</span>AU<span class="sc">:1.3}</span><span class="ss"> au"</span>)</span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="bu">print</span>(<span class="ss">f"Average distance Earth-Sun = </span><span class="sc">{</span>AU<span class="sc">:1.3e}</span><span class="ss"> km = 1 au"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Distance Earth-Sun at aphelion (most distant) = 1.521e+08 km = 1.017 au
Distance Earth-Sun at perihelion (closest) = 1.471e+08 km = 0.983 au
Average distance Earth-Sun = 1.496e+08 km = 1 au</code></pre>
</div>
</div>
</section>
</section>
<section id="size-of-our-solar-system" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="size-of-our-solar-system"><span class="header-section-number">1.3.4</span> Size of our solar system</h3>
<table class="table">
<thead>
<tr class="header">
<th>Planet</th>
<th>Distance from Sun (a.u.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mercury</td>
<td>0.39</td>
</tr>
<tr class="even">
<td>Venus</td>
<td>0.72</td>
</tr>
<tr class="odd">
<td>Earth</td>
<td>1</td>
</tr>
<tr class="even">
<td>Mars</td>
<td>1.52</td>
</tr>
<tr class="odd">
<td>Jupiter</td>
<td>5.20</td>
</tr>
<tr class="even">
<td>Saturn</td>
<td>9.54</td>
</tr>
<tr class="odd">
<td>Uranus</td>
<td>19.2</td>
</tr>
<tr class="even">
<td>Neptune</td>
<td>30.06</td>
</tr>
</tbody>
</table>
<div id="fig-solar-distances" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Solar_system_distances.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.5: Distances in the solar system. Planet sizes are not to scale.</figcaption>
</figure>
</div>
<!-- 
<img src="img/Solar_system_distances.png" style="max-height: 300px; base64; display: block; position:relative; float:centre; padding-right:0.5cm"/> -->
</section>
<section id="measuring-the-distance-to-the-stars" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="measuring-the-distance-to-the-stars"><span class="header-section-number">1.3.5</span> Measuring the distance to the stars</h3>
<section id="the-parallax-method" class="level4" data-number="1.3.5.1">
<h4 data-number="1.3.5.1" class="anchored" data-anchor-id="the-parallax-method"><span class="header-section-number">1.3.5.1</span> The parallax method</h4>
<p>We started with the easy example of answering how distant is the Sun, but what about other stars? One way to determine the distance to nearest stars is to use the <em>parallax method</em>.</p>
<p>If you look at the position of a closer object against a further background, you will notice that the image of the near object will shift in the background as you move (see <a href="#fig-parallax1">Figure&nbsp;<span>1.6</span></a>). This effect is called parallax and you can experience it even when you close one eye at the time looking at an object against a background.</p>
<!-- <div>
<img src="img/Parallax_Example.png" width="700"/>
</div> -->
<div id="fig-parallax1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Parallax_Example.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.6: Illustrative example of the parallax method. The background against which the yellow star object is seen changes based on the viewpoint.</figcaption>
</figure>
</div>
<p>Analogously, in a background of distant stars, a closer star will appear to move against them as the Earth orbits the Sun. So how do we use this to determine the distance to a start? We use trigonometry.</p>
<p>The angle formed between the lines of sight of a star from two positions of the observer is twice the parallax angle. <a href="#fig-parallax2">Figure&nbsp;<span>1.7</span></a> shows the parallax as the angle between the lines of sight of the observer on Earth and from the Sun (the middle point between the position of Earth six months apart).</p>
<p>The number of stars that can be observed from Earth is limited and nowadays <em>direct</em> observations of the distance using the parallax method are done by satellites orbiting the Sun in sync with Earth. Hipparcos gathered data on more than one million stars, and its successor Gaia has already observed 2 billion stars!</p>
<!-- <img src="img/parallax_parsecs.webp" style="max-height: 600px; display: block; position:relative; float:right; padding-left:.5cm"> -->
<div id="fig-parallax2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/parallax_parsecs.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.7: Parallax and parsecs representation. Image readapted from: https://www.astronomy.com/wp-content/uploads/sites/2/2023/02/parsec.png</figcaption>
</figure>
</div>
<!-- $\begin{equation} -->
<!-- \end{equation}$ -->
<ul>
<li>The parallax is generally measured in arcseconds (<em>as</em>).</li>
</ul>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Arcseconds - degrees - radians conversion
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
  \mathrm{1 arcsecond} = \dfrac{1}{3600} \deg = \dfrac{1}{206,265} \mathrm{radians}.
\]</span></p>
<p>You can show these conversions by recalling that <span class="math display">\[
  1\ \mathrm{rad} = 57.3\deg = (57.3\times 60\times 60)\ \mathrm{as}=206,265\ \mathrm{as}.
\]</span></p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Parsec definition
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The parsec (<strong>par</strong>allax-<strong>sec</strong>ond, <em>pc</em>) is defined as:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
1\ \mathrm{parsec} &amp;= \dfrac{1 \mathrm{au}}{\mathrm{arcsecond\  in\  radians}} = 206,265\mathrm{au}= \dfrac{648000}{\pi} \mathrm{au}\\
&amp;\approx 3.086\times 10^{16}\mathrm{m}.
\end{aligned}
\]</span></p>
</div>
</div>
<ul>
<li><p>A parallax of 1 arcsecond corresponds to a distance to the star of 1 parsec (3.26 light-years).</p></li>
<li><p>Using trigonometry, the distance <span class="math inline">\(d\)</span> to the star, in astronomical units, is given by:</p></li>
</ul>
<p><span class="math display">\[
    d =\dfrac{1 \mathrm{au}}{\tan p}\simeq \dfrac{1}{p} \mathrm{au}
\]</span> where <span class="math inline">\(p\)</span> is the parallax, and for this approximation we used <span class="math inline">\(p\)</span> measured in radians. Converting the parallax <span class="math inline">\(p\)</span> to <span class="math inline">\(p''\)</span>, from radians to arcseconds, we obtain the distance in parsec: <span class="math display">\[
    d \simeq\dfrac{206,265 \mathrm{au}}{p''}= \dfrac{1}{p''} \mathrm{pc}
\]</span></p>
<div class="cell" data-execution_count="3">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="im">import</span> math</span>
<span id="cb5-3"><a href="#cb5-3"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>pc <span class="op">=</span> <span class="dv">648000</span><span class="op">/</span>np.pi<span class="op">*</span>AU <span class="co"># km</span></span>
<span id="cb5-5"><a href="#cb5-5"></a><span class="bu">print</span>(<span class="ss">f"1parsec = </span><span class="sc">{</span>pc<span class="sc">:1.3e}</span><span class="ss"> km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1parsec = 3.086e+13 km</code></pre>
</div>
</div>
</section>
<section id="the-nearest-star-proxima-centauri" class="level4" data-number="1.3.5.2">
<h4 data-number="1.3.5.2" class="anchored" data-anchor-id="the-nearest-star-proxima-centauri"><span class="header-section-number">1.3.5.2</span> The nearest star: Proxima Centauri</h4>
<p>The further a star is, the smaller the parallax angle.</p>
<p>The nearest star (Proxima Centauri) has a parallax of 0.7681 arcseconds. This is <em>very</em> tiny, but still, we are able to measure it! To give you an idea of how small this is:</p>
<ul>
<li>It is approximately the angle subtended by an object having a diameter of 2 centimeters, positioned at a distance of 5.3km!</li>
<li>The shift produced by the parallax against the background would be <span class="math inline">\(1/2000^{th}\)</span> the width of the Full Moon!</li>
</ul>
<p>The parallax method is covered in other courses, so this is just a taster, but now knowing the parallax of Proxima Centauri (or another star), we can find the distance to that.</p>
<div class="cell" data-execution_count="4">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a><span class="im">import</span> math</span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-3"><a href="#cb7-3"></a><span class="kw">def</span> arcsec_to_rad(p):</span>
<span id="cb7-4"><a href="#cb7-4"></a>    rad <span class="op">=</span> p<span class="op">/</span><span class="dv">206265</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>    <span class="cf">return</span> rad</span>
<span id="cb7-6"><a href="#cb7-6"></a></span>
<span id="cb7-7"><a href="#cb7-7"></a>p <span class="op">=</span> <span class="fl">0.7681</span> <span class="co"># as</span></span>
<span id="cb7-8"><a href="#cb7-8"></a>d_pc <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>p <span class="co"># pc</span></span>
<span id="cb7-9"><a href="#cb7-9"></a></span>
<span id="cb7-10"><a href="#cb7-10"></a>p_rad <span class="op">=</span> arcsec_to_rad(p)</span>
<span id="cb7-11"><a href="#cb7-11"></a>d_au <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>p_rad <span class="co">#&nbsp;au</span></span>
<span id="cb7-12"><a href="#cb7-12"></a>d_km <span class="op">=</span> d_au<span class="op">*</span>AU <span class="co"># km</span></span>
<span id="cb7-13"><a href="#cb7-13"></a><span class="bu">print</span>(<span class="ss">f"p = </span><span class="sc">{</span>p<span class="sc">}</span><span class="ss"> as"</span>)</span>
<span id="cb7-14"><a href="#cb7-14"></a><span class="bu">print</span>(<span class="ss">f"d = 1/p pc = 1/</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss"> pc = </span><span class="sc">{</span>d_pc<span class="sc">:1.1e}</span><span class="ss"> pc"</span>)</span>
<span id="cb7-15"><a href="#cb7-15"></a><span class="bu">print</span>(<span class="ss">f"d = 1/p pc = 206265/p au = 206265/</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss"> au = </span><span class="sc">{</span>d_au<span class="sc">:1.1e}</span><span class="ss"> au"</span>)</span>
<span id="cb7-16"><a href="#cb7-16"></a><span class="bu">print</span>(<span class="ss">f"d = </span><span class="sc">{</span>d_au<span class="sc">:1.1e}</span><span class="ss"> au * 149597870 km = </span><span class="sc">{</span>d_km<span class="sc">:1.1e}</span><span class="ss"> km"</span>)</span>
<span id="cb7-17"><a href="#cb7-17"></a><span class="bu">print</span>(<span class="ss">f"The distance from Proxima Centauri is = </span><span class="sc">{</span>d_pc<span class="sc">:1.1e}</span><span class="ss"> pc = </span><span class="sc">{</span>d_au<span class="sc">:1.1e}</span><span class="ss"> au = </span><span class="sc">{</span>d_km<span class="sc">:1.1e}</span><span class="ss"> km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>p = 0.7681 as
d = 1/p pc = 1/0.7681 pc = 1.3e+00 pc
d = 1/p pc = 206265/p au = 206265/0.7681 au = 2.7e+05 au
d = 2.7e+05 au * 149597870 km = 4.0e+13 km
The distance from Proxima Centauri is = 1.3e+00 pc = 2.7e+05 au = 4.0e+13 km</code></pre>
</div>
</div>
</section>
<section id="spot-the-mistake-question" class="level4" data-number="1.3.5.3">
<h4 data-number="1.3.5.3" class="anchored" data-anchor-id="spot-the-mistake-question"><span class="header-section-number">1.3.5.3</span> <span style="color:#336699;">‘Spot the mistake’ question:</span></h4>
<p>An unknown star has a parallax of 379.21 mas. Your messy lecturer tried to calculate the distance to the star but she must have made some mistakes because something looks wrong. Can you tell what?</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># This is the version with mistakes</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="im">import</span> math</span>
<span id="cb9-3"><a href="#cb9-3"></a></span>
<span id="cb9-4"><a href="#cb9-4"></a>p <span class="op">=</span> <span class="fl">379.21</span><span class="op">/</span><span class="dv">10000</span> <span class="co"># as </span></span>
<span id="cb9-5"><a href="#cb9-5"></a>d_pc <span class="op">=</span> <span class="dv">206265</span><span class="op">/</span>p <span class="co"># pc</span></span>
<span id="cb9-6"><a href="#cb9-6"></a></span>
<span id="cb9-7"><a href="#cb9-7"></a>d_au <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>p <span class="co">#&nbsp;au</span></span>
<span id="cb9-8"><a href="#cb9-8"></a></span>
<span id="cb9-9"><a href="#cb9-9"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb9-10"><a href="#cb9-10"></a>d_km <span class="op">=</span> d_au<span class="op">*</span>AU <span class="co"># km</span></span>
<span id="cb9-11"><a href="#cb9-11"></a><span class="bu">print</span>(<span class="ss">f"The distance to the star is = </span><span class="sc">{</span>d_pc<span class="sc">:1.1e}</span><span class="ss"> pc = </span><span class="sc">{</span>d_au<span class="sc">:1.1e}</span><span class="ss"> au = </span><span class="sc">{</span>d_km<span class="sc">:1.1e}</span><span class="ss"> km? Something does not look right... find the mistakes!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The distance to the star is = 5.4e+06 pc = 2.6e+01 au = 3.9e+09 km? Something does not look right… find the mistakes!</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<details>
<summary>
Hint 1
</summary>
Check the orders of magnitude, do they seem reasonable?
</details>
<details>
<summary>
Hint 2
</summary>
Compare these orders of magnitude with the ones found for Proxima Centauri, any red flags?
</details>
<details>
<summary>
Hint 3
</summary>
The units are important!
</details>
</div>
</div>
</div>
<!-- ```{python}
# The version with mistakes, where I made a wrong units conversion and I swapped the formulas for d in pc and in au
import warnings
warnings.filterwarnings('ignore')
import math

p = 379.21/10000 # as 
d_pc = 206265/p # pc

d_au = 1/p # au

AU = 149597870 # km
d_km = d_au*AU # km
print(f"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km? Something does not look right... find the mistakes!") -->
<details>
<summary>
<strong>Solution</strong>
</summary>
<p>Below is the solution to the question. Something was clearly wrong with the orders of magnitudes of the values obtained in the wrong solution:</p>
<ul>
<li>the distance in pc can not be larger than the distance in au! Those orders of magnitude are clearly off!</li>
<li>if you compare this with the values obtained for Proxima Centauri, you should expect approximately the same orders of magnitude</li>
<li><span class="math inline">\(10^6\)</span> pc would be way too far to be able to use the parallax method to measure the distance: the most precise and reliable measurements of the parallax (with the Hubble Space Telescope and Gaia space mission), can measure distances of the order of <span class="math inline">\(10^3\mathrm{pc}\)</span>.</li>
</ul>
<!-- ```python 
# The correct version
import warnings
warnings.filterwarnings('ignore')
import math

p = 379.21/1000 # as <- the units conversion was wrong
d_pc = 1/p # pc <- This formula for the distance in pc was swapped with the one below for the distance in au

d_au = 206265/p # au <-

AU = 149597870 # km
d_km = d_au*AU # km
print(f"The distance to the star is = {d_pc:1.1e} pc = {d_au:1.1e} au = {d_km:1.1e} km
```
The distance to the star is = 2.6e+00 pc = 5.4e+05 au = 8.1e+13 km -->
<div class="cell" data-execution_count="5">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># The correct version</span></span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="im">import</span> math</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a>p <span class="op">=</span> <span class="fl">379.21</span><span class="op">/</span><span class="dv">1000</span> <span class="co"># as &lt;- the units conversion was wrong</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>d_pc <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>p <span class="co"># pc &lt;- This formula for the distance in pc was swapped with the one below for the distance in au</span></span>
<span id="cb10-6"><a href="#cb10-6"></a></span>
<span id="cb10-7"><a href="#cb10-7"></a>d_au <span class="op">=</span> <span class="dv">206265</span><span class="op">/</span>p <span class="co">#&nbsp;au</span></span>
<span id="cb10-8"><a href="#cb10-8"></a></span>
<span id="cb10-9"><a href="#cb10-9"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb10-10"><a href="#cb10-10"></a>d_km <span class="op">=</span> d_au<span class="op">*</span>AU <span class="co"># km</span></span>
<span id="cb10-11"><a href="#cb10-11"></a><span class="bu">print</span>(<span class="ss">f"The distance to the star is = </span><span class="sc">{</span>d_pc<span class="sc">:1.1e}</span><span class="ss"> pc = </span><span class="sc">{</span>d_au<span class="sc">:1.1e}</span><span class="ss"> au = </span><span class="sc">{</span>d_km<span class="sc">:1.1e}</span><span class="ss"> km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The distance to the star is = 2.6e+00 pc = 5.4e+05 au = 8.1e+13 km</code></pre>
</div>
</div>
</details>
</section>
</section>
<section id="transit-method" class="level3" data-number="1.3.6">
<h3 data-number="1.3.6" class="anchored" data-anchor-id="transit-method"><span class="header-section-number">1.3.6</span> Transit method</h3>
<p><img src="img/HalGreg.jpg" style="max-height: 200px; display:block; position:relative; float:left; padding-right:1cm"> The parallax was also originally proposed as a way to determine the distance to the Sun by the Scottish astronomer James Gregory, in 1663, using the transit of Venus. Gregory is seldom given any credits for this idea and usually all the credits goes to Edmund Halley for some reason (can anyone find out why?).</p>
<p>In 1677, at the age of 20, Halley travelled to St Helena to map the Southern Skies and observed a transit of Mercury on November 7th. Like Gregory, he suggested that the transit of a planet like Venus could be used as a method to measure the distance to the Sun, using parallax.</p>
<p><a href="https://eclipse.gsfc.nasa.gov/transit/HalleyParallax.html">Here</a> is the translation of Halley’s publication about this idea.</p>
<div id="fig-Venus-transit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/VenusTransit.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.8: A composite image of the June 2004 transit of Venus as seen from Waldenburg, Germany. Credit: E. SLAWIK/SPL</figcaption>
</figure>
</div>
<!-- <img src="img/VenusTransit.png" style="max-height: 500px; display: block; position:relative; float:left; padding-right:1cm"> -->
<div id="fig-transit-method" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/TransitMethod.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.9: Representation of the transit method</figcaption>
</figure>
</div>
<p>According to ‘Halley’s method’, two observers (A and B in the figure above) have to be positioned at a great distance from each other, but both located on the side of Earth facing the Sun at the time of the transit. Each observer would precisely measure the times that Venus appear to be in different positions (contact points) relative to the Sun. The observers would see different chords of the planet’s trajectory across the disk of the sun due to parallax. Venus forms two similar triangles with the Earth and the Sun at their opposite edges. Since the triangles are similar, the projected distance on the Sun can be found by comparing it to a known baseline on Earth. Once the angle shift is measured, the distances to Venus and then to the Sun can be determined using trigonometry.</p>
<p>Modern techniques use radar echo ranging to measure distances in the Solar System very precisely.</p>
<!-- Venus forms two similar triangles with the Earth and the Sun at their opposite edges. Since the triangles are similar, the projected distance on the Sun can be found by comparing to a known baseline on Earth. -->
</section>
</section>
<section id="how-big-are-stars" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="how-big-are-stars"><span class="header-section-number">1.4</span> How big are stars?</h2>
<section id="how-big-is-the-sun" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="how-big-is-the-sun"><span class="header-section-number">1.4.1</span> How big is the Sun?</h3>
<!-- ![](img/AngularDiameter.png){#fig-angular-diameter width=25% fig-align="right" fig-alt="Geometrical configuration of the Sun as seen from an observer at distance D."} -->
<p><img style="float: right; max-height: 350px; position:relative;" src="img/AngularDiameter.png"></p>
<p>We can deduce the width of the sun if we know its angular diameter <span class="math inline">\(\alpha\)</span> and the distance <span class="math inline">\(D\)</span>.</p>
<p>For small angles,</p>
<p><span class="math display">\[
\alpha \approx \frac{2R_\odot}{D}.
\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>This formula uses <em>radians</em> for <span class="math inline">\(\alpha\)</span></p>
</div>
</div>
<p>Since the Sun’s angular diameter is <span class="math inline">\(\alpha\approx 0.5^\circ \approx 32 \ \mathrm{arcmin} \approx 9.3\times 10^{-3} \mathrm{rad}\)</span>, and we know its distance (from Earth) <span class="math inline">\(D = 1 \mathrm{au} = 149,597,870 \ \mathrm{km}\)</span>, we can now calculate the size of the Sun using the equation above.</p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;fragment&quot;}" data-execution_count="6">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1"></a><span class="im">import</span> math</span>
<span id="cb12-2"><a href="#cb12-2"></a>AU <span class="op">=</span> <span class="dv">149597870</span> <span class="co"># km</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>ang_diameter_arcm <span class="op">=</span> <span class="dv">32</span> <span class="co"># angular diameter of Sun is about 32 minutes of arc</span></span>
<span id="cb12-4"><a href="#cb12-4"></a>ang_diameter <span class="op">=</span> ang_diameter_arcm<span class="op">/</span><span class="dv">60</span> <span class="op">*</span> math.pi<span class="op">/</span><span class="dv">180</span> </span>
<span id="cb12-5"><a href="#cb12-5"></a><span class="co"># ang_diameter = ang_diameter_rad</span></span>
<span id="cb12-6"><a href="#cb12-6"></a>diameter <span class="op">=</span> AU <span class="op">*</span> ang_diameter</span>
<span id="cb12-7"><a href="#cb12-7"></a><span class="bu">print</span>(<span class="ss">f"1 au = </span><span class="sc">{</span>AU<span class="sc">:1.3e}</span><span class="ss"> km"</span>)</span>
<span id="cb12-8"><a href="#cb12-8"></a><span class="bu">print</span>(<span class="ss">f"angular diameter of the sun =  </span><span class="sc">{</span>ang_diameter<span class="sc">:.3e}</span><span class="ss"> radians"</span>)</span>
<span id="cb12-9"><a href="#cb12-9"></a><span class="bu">print</span>(<span class="ss">f"Diameter of Sun = </span><span class="sc">{</span>diameter<span class="sc">:.0f}</span><span class="ss"> km"</span>)</span>
<span id="cb12-10"><a href="#cb12-10"></a><span class="bu">print</span>(<span class="ss">f"Radius of Sun = </span><span class="sc">{</span>diameter<span class="op">/</span><span class="dv">2</span><span class="sc">:.0f}</span><span class="ss"> km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1 au = 1.496e+08 km
angular diameter of the sun =  9.308e-03 radians
Diameter of Sun = 1392520 km
Radius of Sun = 696260 km</code></pre>
</div>
</div>
<p>The accepted radius is <span class="math inline">\(6.957\times 10^5\)</span> km.</p>
</section>
<section id="what-about-other-stars" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="what-about-other-stars"><span class="header-section-number">1.4.2</span> What about other stars?</h3>
<p>Here is a video showing a comparison between star sizes: https://www.youtube.com/watch?v=HEheh1BH34Q <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/HEheh1BH34Q?si=BQb-tLiTvei87S7Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen=""></iframe></p>
<section id="a-comparison-of-some-star-sizes" class="level4" data-number="1.4.2.1">
<h4 data-number="1.4.2.1" class="anchored" data-anchor-id="a-comparison-of-some-star-sizes"><span class="header-section-number">1.4.2.1</span> A comparison of some star sizes</h4>
<p>Here is a list of some selected examples of star radii, compared to the Sun. Some stars, such as Sirius B, are much smaller than the Sun. (<a href="#fig-siriusAB">Figure&nbsp;<span>1.10</span></a> below shows an artistic impression of Sirius A and Sirius B.)</p>
<p>The typical range of star radii is roughly <span class="math inline">\(10^{-3}R_\odot &lt; R &lt; 10^3 R_\odot\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th>Name</th>
<th>Radius</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sirius B</td>
<td>0.008 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="even">
<td>Sirius A</td>
<td>1.71 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="odd">
<td>Arcturus</td>
<td>12 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="even">
<td>Aldebaran</td>
<td>22 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="odd">
<td>Rigel</td>
<td>78.9 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="even">
<td>Mira</td>
<td>210 <span class="math inline">\(R_\odot\)</span></td>
</tr>
<tr class="odd">
<td>Betelgeuse</td>
<td>320 <span class="math inline">\(R_\odot\)</span></td>
</tr>
</tbody>
</table>
<!-- <img src="img/siriusAB.jpeg" style="max-height: 500px; display: block; position:relative; float:right; padding-right:1cm"> -->
<div id="fig-siriusAB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/siriusAB.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.10: Artistic impression of Sirius A (large blue-white star on the left) and Sirius B (small blue white-dwarf star on the right). <em>Image credit: NASA, ESA and G. Bacon (STScI)</em></figcaption>
</figure>
</div>
<ul>
<li>Sirius B is a very small but very hot white dwarf. It is even smaller than Earth, and it cannot be observed by the naked eye. Its companion star Sirius A, in contrast, is the brightest star in the sky</li>
<li>Betelgeuse – at a distance of 650 l.y. is a red supergiant and rather short-lived star, the second brightest in Orion and the ninth brightest in the sky</li>
<li>It’s close to the end of its life and en-route to a rather spectacular death within a million years or so</li>
<li>For Betelgeuse, the angular diameter <span class="math inline">\(\alpha\)</span> is about 0.000014 degrees (<span class="math inline">\(1.4\times 10^{-5}\)</span> degrees)</li>
<li>Most stars have a much smaller angular diameter and cannot be directly imaged</li>
<li>We have to deduce their size indirectly! (more on this later)</li>
</ul>
<div id="fig-betelgeuse" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Betelgeuse.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.11: Betelgeuse. <em>Image credit: ALMA (ESO/NAOJ/NRAO)/E. O’Gorman/P. Kervella</em></figcaption>
</figure>
</div>
</section>
</section>
<section id="a-handy-guide-to-estimating-angular-diameters" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="a-handy-guide-to-estimating-angular-diameters"><span class="header-section-number">1.4.3</span> A <em>handy</em> guide to estimating angular diameters</h3>
<p>You can estimate angular diameters using your hand! Extend your arm, place the hand at a right angle and follow the intstructions of <a href="#fig-handy-guide">Figure&nbsp;<span>1.12</span></a> to estimate different angles. This may not be useful to determine the size of objects that are very far and appear too small, such as stars, but can be useful to measure the angular distance between two stars.</p>
<div id="fig-handy-guide" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/measuring-sky-with-hand.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.12: How to use hands to measure angular distances in the sky</figcaption>
</figure>
</div>
</section>
<section id="how-far-apart-are-the-stars" class="level3" data-number="1.4.4">
<h3 data-number="1.4.4" class="anchored" data-anchor-id="how-far-apart-are-the-stars"><span class="header-section-number">1.4.4</span> How far apart are the stars?</h3>
<p>Let’s have a look at some orders of magnitude (this is a good resource if you want to visualise them: https://scaleofuniverse.com/en-gb).</p>
<ul>
<li>The nearest star (Proxima Centauri) is about <span class="math inline">\(10^{16}\)</span> m away.</li>
<li>Diameter of the Sun ~ <span class="math inline">\(10^{9}\)</span> m.</li>
<li>The difference in scale is <span class="math inline">\(10^7\)</span>m in distance, or <span class="math inline">\(10^{21}\)</span>m<span class="math inline">\(^3\)</span> in volume.</li>
<li>Relative to their size, stars are the most isolated structures in the universe.</li>
<li>If stars were grains of sand (~1 mm), they would be ~10 km apart!</li>
<li>However, we find them in clusters and binaries - what explains this? (more on this later)</li>
</ul>
</section>
</section>
<section id="how-bright-are-stars" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="how-bright-are-stars"><span class="header-section-number">1.5</span> How bright are stars?</h2>
<p>If we try to answer this question based on our observations, we have to keep in mind that the apparent brightness of a light source will vary depending on its distance from the observer. The brightenss we observe is therefore not an <em>intrinsic</em> property of the stars, as it depends on the distance between the observer and the stars.</p>
<p>This is the reason why we need to differentiate between the <em>apparent brightness</em> of a star and its <em>luminosity</em>.</p>
<section id="apparent-brightness-and-luminosity" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="apparent-brightness-and-luminosity"><span class="header-section-number">1.5.1</span> Apparent brightness and luminosity</h3>
<p>The <strong>apparent brightness</strong>, <span class="math inline">\(F\)</span>, also referred to as the <em>radiant flux</em> or <em>power flux</em>, is the total amount of energy emitted by a star, per unit time, crossing an unit area (units [<span class="math inline">\(\mathrm{W/m}^2\)</span>]). It is <em>not</em> an intrinsic property of a star, because it depends on the distance from the star.</p>
<p><a href="#fig-inverse-square-law">Figure&nbsp;<span>1.13</span></a> can give you a better understanding of that. Each square represents an unit area. The lightbulb, like a star, radiates equally in every direction (i.e.&nbsp;isotropically). The ‘rays’ coming out of the light source represent the flux. The farther the position of the observer is from the source, the less flux the observer, in one unit area, will receive. The relationship between the power flux, <span class="math inline">\(F\)</span>, and the distance to the source, <span class="math inline">\(r\)</span>, is given by the inverse square law: <span class="math display">\[F\propto \dfrac{1}{r^2}.\]</span> Since the light source radiates isotropically (even though the figure below shows only a portion of the rays), the power flux <span class="math inline">\(F\)</span> is equal across all parts of the sphere at a given distance.</p>
<div id="fig-inverse-square-law" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/inverse_square_law.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.13: Inverse square law of the radiant flux of a light source</figcaption>
</figure>
</div>
<p>The <strong>Luminosity</strong> of a star, <span class="math inline">\(L\)</span>, measured in Watts (W) or equivalently Joules per second (J/s), is its energy output per unit time. The luminosity is the <em>total</em> energy radiated in all the directions in an unit time and it does not depend on the distance from the observer: it is an <em>intrinsic</em> property of the star.</p>
<p>How are these two quantities related?</p>
<p>Imagine a sphere of radius <span class="math inline">\(r\)</span> centered on a star, which is isotropically radiating. We saw that the luminosity (energy output per unit time) does not depend upon the distance, but the radiant flux <span class="math inline">\(F\)</span> does. To find the power flux <span class="math inline">\(F\)</span>, we need to divide the luminosity equally over the area of the sphere, <span class="math inline">\(4\pi r^2\)</span>. Therefore <span id="eq-flux"><span class="math display">\[
F = \frac{L}{4\pi r^2}
\tag{1.1}\]</span></span></p>
<p>The apparent brightness depends on the luminosity and on the distance of the observer from the star. From <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a>, you can see how two stars of equal luminosity, located at different distances from Earth, would have different apparent brightness.</p>
<p><em>Photometry</em> is the measurement of the quantity of light from a star, i.e.&nbsp;the flux of energy per unit time, per unit area, that we receive at Earth.</p>
<p>For a particular star, if we know the luminosity (<span class="math inline">\(L\)</span>) of the star and its distance from Earth (<span class="math inline">\(r\)</span>), we can calculate the radiant flux using <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a>.</p>
<section id="the-suns-luminosity" class="level4" data-number="1.5.1.1">
<h4 data-number="1.5.1.1" class="anchored" data-anchor-id="the-suns-luminosity"><span class="header-section-number">1.5.1.1</span> The Sun’s luminosity</h4>
<p>For our Sun, we have: <span id="eq-solar-constant"><span class="math display">\[
F_{\odot} = 1361 \mathrm{W/m^2},
\tag{1.2}\]</span></span></p>
<p>The “Solar Constant”, or “Solar irradiance” - sometimes indicated with the symbol <span class="math inline">\(S_\odot\)</span> in textbooks - and</p>
<p><span class="math inline">\(r = 1 ~\mathrm{a.u.} \approx 1.5\times 10^{11}\mathrm{m}\)</span>.</p>
<p>Therefore, using <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a>:</p>
<p><span class="math inline">\(L_\odot = 4\pi r^2 F = 3.8275 \times 10^{26} ~\mathrm{W}\)</span></p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;skip&quot;}" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a><span class="im">import</span> scipy</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="im">from</span> scipy.constants <span class="im">import</span> pi, au, parsec</span>
<span id="cb14-3"><a href="#cb14-3"></a></span>
<span id="cb14-4"><a href="#cb14-4"></a>F <span class="op">=</span> <span class="fl">1361.0</span> <span class="co"># W/m/m</span></span>
<span id="cb14-5"><a href="#cb14-5"></a>r <span class="op">=</span> au <span class="co"># m</span></span>
<span id="cb14-6"><a href="#cb14-6"></a>L <span class="op">=</span> F<span class="op">*</span><span class="dv">4</span><span class="op">*</span>pi<span class="op">*</span>r<span class="op">**</span><span class="dv">2</span></span>
<span id="cb14-7"><a href="#cb14-7"></a></span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="bu">print</span>(<span class="ss">f'Power flux: F = </span><span class="sc">{</span>F<span class="sc">}</span><span class="ss"> W/m/m'</span>)</span>
<span id="cb14-9"><a href="#cb14-9"></a><span class="bu">print</span>(<span class="ss">f'r = 1au = </span><span class="sc">{</span>r<span class="sc">:1.4e}</span><span class="ss"> m'</span>)</span>
<span id="cb14-10"><a href="#cb14-10"></a><span class="bu">print</span>(<span class="ss">f'Luminosity: L =  F*4*pi*r**2 = </span><span class="sc">{</span>L<span class="sc">:1.4e}</span><span class="ss"> W'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Power flux: F = 1361.0 W/m/m
r = 1au = 1.4960e+11 m
Luminosity: L =  F*4*pi*r**2 = 3.8275e+26 W</code></pre>
</div>
</div>
<p>For other stars there is a large range of luminosities:</p>
<p><span class="math inline">\(10^{-4}\,L_\odot &lt; L &lt; 10^{6}\,L_\odot\)</span></p>
<p>If we think of the least luminous star as a 100W incandescent lightbulb, this huge range tells us that the most luminous star would be like the entire world’s power output.</p>
<p>Why is there this very large range? We will answer this question in the next lectures.</p>
</section>
<section id="spot-the-mistake-question-1" class="level4" data-number="1.5.1.2">
<h4 data-number="1.5.1.2" class="anchored" data-anchor-id="spot-the-mistake-question-1"><span class="header-section-number">1.5.1.2</span> <span style="color:#336699;">‘Spot the mistake’ question:</span></h4>
<p>What would the apparent brightness be for a star like the Sun at a distance of 10 pc?</p>
<p>Something does not seem to make sense in the answer below, why?</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># This is the version containing a mistake</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="im">import</span> math</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-4"><a href="#cb16-4"></a>L <span class="op">=</span> <span class="fl">3.8275E26</span> <span class="co"># W</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>r <span class="op">=</span> <span class="dv">10</span> <span class="co">#pc</span></span>
<span id="cb16-6"><a href="#cb16-6"></a>F <span class="op">=</span> L<span class="op">/</span>(<span class="dv">4</span><span class="op">*</span>np.pi<span class="op">*</span>r<span class="op">**</span><span class="dv">2</span>) <span class="co"># W/m^2</span></span>
<span id="cb16-7"><a href="#cb16-7"></a><span class="bu">print</span>(<span class="ss">f'Solar luminosity: L = </span><span class="sc">{</span>L<span class="sc">}</span><span class="ss"> W'</span>)</span>
<span id="cb16-8"><a href="#cb16-8"></a><span class="bu">print</span>(<span class="ss">f'Distance: r = </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss"> pc'</span>)</span>
<span id="cb16-9"><a href="#cb16-9"></a><span class="bu">print</span>(<span class="ss">f'Apparent brightness of the Sun at 10 parsec: F = L/(4*pi*r^2) = </span><span class="sc">{</span>F<span class="sc">:1.4e}</span><span class="ss"> W/m/m'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Solar luminosity: L = 3.8275e+26 W</p>
<p>Distance: r = 10 pc</p>
<p>Apparent brightness of the Sun at 10 parsec: <span class="math inline">\(F = \frac{L}{4\pi r^2} = 3.0458\times 10^{23} W/m^2\)</span></p>
<!-- ```python
# This is the version containing a mistake
L = 3.8275E26 # W
r = 10 #pc
F = L/(4*pi*r**2)
print(f'Solar luminosity = {L} W')
print(f'Distance r = {r} pc')
print(f'Apparent brightness of the Sun at 10 parsec: F = {F} W/m/m') -->
<!-- ```
Solar luminosity = 3.8275e+26 W
Distance r = 10 pc
Apparent brightness of the Sun at 10 parsec: F = 3.0458e+23 W/m/m
``` -->
<p>Does this make sense?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<details>
<summary>
Hint 1
</summary>
Compare this apparent brightness obtained below with the value of the power flux used (the Solar constant) in the previous example. What is wrong?
</details>
<details>
<summary>
Hint 2
</summary>
Do a ‘sanity check’ of the units in the quantities used above. Does it seem correct?
</details>
</div>
</div>
</div>
<details>
<summary>
Solution
</summary>
<p>If we compare this value obtained for the apparent brightness, <span class="math inline">\(F=3.046\times 10^{23} \mathrm{W/m}^2\)</span>, with the Solar constant used in the previous example, <span class="math inline">\(F_\odot = 1361 \mathrm{W/m}^2\)</span>, we can immediately notice that something is wrong by just looking at the extreme difference in the orders of magnitude. If we are observing the Sun from a further position of 10pc instead of 1au, we cannot expect it to appear brighter!</p>
<p><em>‘Sanity check’</em>: Let’s check the units of the quantities given above, replacing them in <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a>: <span class="math display">\[ F=\frac{L}{4\pi r^2} \implies [W/m^2] = \frac{[W]}{[pc]^2} \]</span>. This does not return an identity since <span class="math inline">\([m]\neq [pc]\)</span>, so now we know where made a mistake, by just checking the units!</p>
<p>To calculate the value of the flux correctly, you need to convert the distance from parsecs to meters, because the flux should be written in units of [<span class="math inline">\(W/m^2\)</span>]!</p>
<p>The correct answer is:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1"></a><span class="co">#&nbsp;Correct version</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="im">import</span> scipy</span>
<span id="cb17-3"><a href="#cb17-3"></a><span class="im">from</span> scipy.constants <span class="im">import</span> pi, parsec</span>
<span id="cb17-4"><a href="#cb17-4"></a>L <span class="op">=</span> <span class="fl">3.8275E26</span> <span class="co"># W</span></span>
<span id="cb17-5"><a href="#cb17-5"></a>r <span class="op">=</span> <span class="dv">10</span><span class="op">*</span>parsec <span class="co">#m</span></span>
<span id="cb17-6"><a href="#cb17-6"></a>F <span class="op">=</span> L<span class="op">/</span>(<span class="dv">4</span><span class="op">*</span>pi<span class="op">*</span>r<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb17-7"><a href="#cb17-7"></a><span class="bu">print</span>(<span class="ss">f'Solar luminosity: L = </span><span class="sc">{</span>L<span class="sc">}</span><span class="ss"> W'</span>)</span>
<span id="cb17-8"><a href="#cb17-8"></a><span class="bu">print</span>(<span class="ss">f'Distance: r = </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss"> pc'</span>)</span>
<span id="cb17-9"><a href="#cb17-9"></a><span class="bu">print</span>(<span class="ss">f'Apparent brightness of the Sun at 10 parsec: F = L/(4*pi*r^2) = </span><span class="sc">{</span>F<span class="sc">:1.4e}</span><span class="ss"> W/m/m'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Solar luminosity: L = 3.8275e+26 W</p>
<p>Distance: r = 10 pc = 3.0857e+17 m</p>
Apparent brightness of the Sun at 10 parsec: <span class="math inline">\(F = \frac{L}{4\pi r^2} = 3.1989\times 10^{-10} W/m^2\)</span>.
</details>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sanity checks
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Always be careful about the units used or units conversions!</p>
<p>Get the habit of doing ‘sanity checks’: check the dimensional analysis and units when you use or derive formulas. This will help you spot some mistakes quickly and it is incredibly useful to rederive some formulas sometime.</p>
</div>
</div>
</div>
<p>In <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a> for instance, we know that the apparent brightness <span class="math inline">\(F\)</span> has units of [W/m <span class="math inline">\(^2\)</span>] and that the luminosity <span class="math inline">\(L\)</span> has units of [W]. Writing the units of each side of the equation, we see that: <span class="math inline">\([W/m^2]=\dfrac{[W]}{[m^2]}\)</span>, which as expected satisfies the identity, meaning that the formula is dimensionally correct.</p>
</section>
</section>
<section id="apparent-magnitude" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="apparent-magnitude"><span class="header-section-number">1.5.2</span> Apparent magnitude</h3>
<p>The flux from even nearby stars is tiny, but many bright stars are distinguished by the naked eye. The human eye (like hearing) responds logarithmically to stimulus. When comparing the flux densities of three stars in a 1:10:100 ratio, the perceived brightness gap between the first and second star appears to be the same as the difference between the second and third star. This equality in perceived brightness gaps illustrates that human perception of brightness operates on a logarithmic scale. Therefore, before modern photometry, astronomers had a scale based on their own naked-eye observations: <strong>stellar (apparent) magnitude</strong>.</p>
<p>This system to measure the stars brightness was first introduced by the Greek astronomer Hipparchos, who compiled a catalog of 850 stars with their positions and their <em>apparent magnitudes</em> on a scale from <span class="math inline">\(m=1\)</span>, being the brightest stars, to <span class="math inline">\(m=6\)</span>, being the faintest stars. The apparent magnitude depends on the position of the observer the same way as the flux does (in fact, we will see in the following how these two quantities are related).</p>
<p>The image below shows an example of a star catalog created by ancient Greek astronomers.</p>
<div id="fig-Almagest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Almagest.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.14: <em>Almagest</em> Ptolemy, c.&nbsp;150AD image credit: Bibliothèque Nationale, Paris</figcaption>
</figure>
</div>
<p>The English translation reads</p>
<div id="fig-Almagest-translated" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/AlmagestTranslation.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.15: Almagest translated</figcaption>
</figure>
</div>
<p>We can still recognise the constellations and find these stars today!</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/littlebear.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><small>Ursa Minor constellation and magnitude scale. Image credit: By IAU and Sky &amp; Telescope magazine (Roger Sinnott &amp; Rick Fienberg) - <a rel="nofollow" class="external autonumber" href="http://www.iau.org/public/constellations/">[1]</a>, <a href="https://creativecommons.org/licenses/by/3.0" title="Creative Commons Attribution 3.0">CC BY 3.0</a>, <a href="https://commons.wikimedia.org/w/index.php?curid=15412502">Link</a> </small></figcaption>
</figure>
</div>
<p>The modern names and magnitudes for these stars are reported in the table below.</p>
<table class="table">
<thead>
<tr class="header">
<th>Modern Name</th>
<th>Magnitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Polaris</td>
<td>1.98</td>
</tr>
<tr class="even">
<td>Yildun</td>
<td>4.35</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\epsilon\)</span> Umi</td>
<td>4.21</td>
</tr>
<tr class="even">
<td>Alasco</td>
<td>4.95</td>
</tr>
<tr class="odd">
<td>Ahfa al Farkadain</td>
<td>4.29</td>
</tr>
<tr class="even">
<td>Pherkad</td>
<td>3.04</td>
</tr>
<tr class="odd">
<td>Kochab</td>
<td>2.07</td>
</tr>
</tbody>
</table>
<p>Note that some of the magnitudes of the little bear stars have changed since ancient times. Partly this is because the scientific definition and measurements are more precise, but also Polaris is a variable star (its brightness changes).</p>
<p>The apparent magnitude scale introduced by Hipparchos has been replaced by Pogson in 1856 and is no longer limited to values between 1 and 6, it now extends between m=-26.83 for the Sun to over m=30 for the faintest object, but the new classification kept these characteristics:</p>
<ul>
<li>5 magnitude steps correspond to a factor of 100 in apparent brightness</li>
<li>A difference of 1 magnitude corresponds to an apparent brightness ratio of <span class="math inline">\(100^{1/5}\simeq 2.512\)</span>, i.e.&nbsp;<span id="eq-magnitude-flux-ratio"><span class="math display">\[\dfrac{F_{m+1}}{F_m}=100^{1/5} \tag{1.3}\]</span></span></li>
<li>Lower magnitudes are <em>brighter</em></li>
<li>The zero point of the apparent magnitude has been <em>conventionally</em> determined.</li>
</ul>
<!-- This is not part of the S.I. system you are familiar with, but it is still widespread in astronomy today. We will learn how to use it in our calculations and relate it to S.I. units. -->
<p>The <em>apparent magnitude</em> <span class="math inline">\(m\)</span> is a measure of a star’s apparent brightness, i.e.&nbsp;the flux received from the star, and it therefore depends on how close the star is to the observer.</p>
<p>The definition of the apparent magnitude is based on the difference between magnitudes and corresponds to the ratio between two stars’ radiant fluxes, as stated in the properties above.</p>
<p>If we consider two stars with measured radiant fluxes (units <span class="math inline">\(W/m^2\)</span>) <span class="math inline">\(F_1\)</span> and <span class="math inline">\(F_2\)</span>, their apparent magnitudes will be related by <span id="eq-apparent-magnitude"><span class="math display">\[
m_1 - m_2 = -2.5 \log_{10} \frac{F_1}{F_2}
\tag{1.4}\]</span></span></p>
<section id="apparent-magnitude-zero-point-convention" class="level4" data-number="1.5.2.1">
<h4 data-number="1.5.2.1" class="anchored" data-anchor-id="apparent-magnitude-zero-point-convention"><span class="header-section-number">1.5.2.1</span> Apparent magnitude zero point convention</h4>
<p>The values of the apparent magnitudes are determined in relation to a zero point value <span class="math inline">\(m=0\)</span>. By convention, this corresponds to the observed flux <span class="math inline">\(F_0\)</span> below.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zero point flux (conventional)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-zero-point-flux"><span class="math display">\[
F_0 = 2.518 × 10^{−8} \ \mathrm{W m}^{−2}.
\tag{1.5}\]</span></span> (Reference: <a href="https://www.iau.org/static/resolutions/IAU2015_English.pdf">IAU 2015 resolution</a>)</p>
</div>
</div>
<p>The apparent magnitude of a star is therefore conventionally defined as</p>
<div class="callout callout-style-default callout-note callout-titled" style="simple">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Apparent magnitude (conventional)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-apparent-magnitude-convention"><span class="math display">\[
m = -2.5 \log_{10}{\frac{F}{F_0}} = -2.5 \log_{10}{F} - 18.997
\tag{1.6}\]</span></span></p>
</div>
</div>
<p>The apparent magnitude depends on the flux, and therefore on the intrinsic luminosity of the star and its distance (<span class="math inline">\(r\)</span>) from Earth.</p>
<p>Using this zero point convention, from the <em>nominal solar flux</em> <span id="eq-sun-flux"><span class="math display">\[
F_\odot = 1361 \mathrm{W/m}^2,
\tag{1.7}\]</span></span> we can find that the apparent magnitude of the Sun is <span id="eq-sun-apparent-magnitude"><span class="math display">\[
m_\odot=-26.382\ \mathrm{mag}.
\tag{1.8}\]</span></span></p>
</section>
</section>
<section id="magnitude-and-units" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="magnitude-and-units"><span class="header-section-number">1.5.3</span> Magnitude and units</h3>
<p>Note that the magnitude is <em>dimensionless</em>, so it does not have units (check this quickly doing dimensional analysis: on the right hand side you have the logarithm of a number, no units). However, to remind us that a value (e.g.&nbsp;<span class="math inline">\(m=-26\)</span>) is a magnitude, you can use the notation ‘mag’ after the numerical value (e.g.&nbsp;<span class="math inline">\(m=-26\)</span> mag).</p>
<div class="callouts-caution">
<p>Beware confusing mass and magnitude when using the same symbol <span class="math inline">\(m\)</span>!</p>
</div>
</section>
<section id="question-1" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="question-1"><span class="header-section-number">1.5.4</span> <span style="color:#336699;">Question</span></h3>
<p>The coefficient in the formula for the apparent magnitude is 2.5. Why is it exactly 2.5 and <em>not</em> <span class="math inline">\(100^{1/5}\simeq 2.512\)</span>?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use the properties of logarithms.</p>
</div>
</div>
</div>
<details>
<summary>
Solution
</summary>
<p>Based on the characteristics of the apparent magnitude listed above, for two stars with apparent magnitudes <span class="math inline">\(m\)</span> and <span class="math inline">\(m+1\)</span>, the ratio between the fluxes is <span class="math display">\[
\frac{F_{m+1}}{F_m}=100^{1/5}.\]</span> How can we rewrite this in a form that explicitely shows the difference between the magnitudes, <span class="math inline">\(m-(m+1)\)</span>?</p>
<p><span class="math display">\[
\begin{aligned}
\dfrac{F_{m+1}}{F_m}=100^{1/5} &amp;\implies \log_{10}{\dfrac{F_{m+1}}{F_m}}=\log_{10}{10^{2/5}}=\frac{2}{5}\log_{10}{10}=\frac{2}{5}\\ &amp;\implies \frac{5}{2}\log_{10}{\dfrac{F_{m+1}}{F_m}} = 1 = (m+1) - m \\
&amp;\implies m-(m+1)=-2.5\log_{10}{\dfrac{F_m}{F_{m+1}}}
\end{aligned}
\]</span></p>
<p>You can see that the factor 2.5 comes from the ratio 5/2 in the derivation of the formula for the apparent magnitude (see the first passage).</p>
<!-- Note that the coefficient in the formula above for the apparent magnitude is 2.5 and _not_ 2.518! Why 2.5? Consider that the flux goes as $r^{-2}$, so $r\propto F^{-1/2}$.
Plug into the apparent magnitude formula and the $1/2$ divides the $5$ into $2.5$. -->
<!-- ### Question

Show that if we have two stars with measured fluxes (units $W/m^2$) $F_1$ and $F_2$, their magnitudes will be related by

$$
\begin{aligned}
m_1 - m_2 = -2.5 \log_10_10_{10} \frac{F_1}{F_2}
\end{aligned}
$$ -->
<!-- __Hint:__

Use the properties of logarithms.

__Solution:__

Having defined the apparent magnitude using the zero point flux above, for the i-th star (i.e. for i=1,2) with flux $F_i$, the apparent magnitude is:
$m_i = -2.5 \log{\dfrac{F_i}{F_0}}$

Therefore:
$$
\begin{aligned*}
m_1 - m_2 & = -2.5 \log{\frac{F_1}{F_0}} - \left(-2.5 \log{\frac{F_2}{F_0}}\right) \\
& = -2.5\log F_1 - ( -2.5\log F_0) - ( -2.5\log F_2 - ( -2.5\log F_0)) \\
& = -2.5 \log F_1 + 2.5 \log F_2\\
& = -2.5 \log{\frac{F_1}{F_2}}
\end{aligned*}
$$ -->
</details></section>
<section id="absolute-magnitude" class="level3" data-number="1.5.5">
<h3 data-number="1.5.5" class="anchored" data-anchor-id="absolute-magnitude"><span class="header-section-number">1.5.5</span> Absolute Magnitude</h3>
<p>Absolute magnitude (M) is a measure solely of the star’s intrinsic luminosity <span class="math inline">\(L,\)</span> so it does <em>not</em> depend on its distance to the observer.</p>
<p>It is conventionally defined as the apparent magnitude of a star at a distance <span class="math inline">\(r=10\mathrm{pc}\)</span>.</p>
<p>If we consider two stars with luminosities <span class="math inline">\(L_1\)</span> and <span class="math inline">\(L_2\)</span>, their absolute magnitudes will be related by</p>
<p><span id="eq-absolute-magnitude"><span class="math display">\[
M_1 - M_2 = -2.5\log_{10}\dfrac{L_1}{L_2}.
\tag{1.9}\]</span></span></p>
<section id="absolute-magnitude-zero-point-convention" class="level4" data-number="1.5.5.1">
<h4 data-number="1.5.5.1" class="anchored" data-anchor-id="absolute-magnitude-zero-point-convention"><span class="header-section-number">1.5.5.1</span> Absolute magnitude zero point convention</h4>
<p>To define the zero point of the absolute magnitude (<span class="math inline">\(M=0\)</span>), we use the same value of the zero flux, <span class="math inline">\(F_0\)</span> (<a href="#eq-zero-point-flux">Equation&nbsp;<span>1.5</span></a>), used to define the apparent magnitude <span class="math inline">\(m=0\)</span>, and we find the corresponding luminosity <span class="math inline">\(L_0\)</span> using <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a> for <span class="math inline">\(r=10\mathrm{pc}\)</span>.</p>
<div class="cell" data-execution_count="8">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1"></a><span class="im">from</span> scipy.constants <span class="im">import</span> pi, parsec</span>
<span id="cb18-2"><a href="#cb18-2"></a>f0 <span class="op">=</span> <span class="fl">2.518021002E-8</span> <span class="co"># W/m/m</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>r <span class="op">=</span> <span class="dv">10</span><span class="op">*</span>parsec <span class="co"># m</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>L0 <span class="op">=</span> <span class="dv">4</span><span class="op">*</span>pi<span class="op">*</span>r<span class="op">**</span><span class="dv">2</span><span class="op">*</span>f0 <span class="co"># W</span></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="bu">print</span>(<span class="ss">f'r = 10 pc = </span><span class="sc">{</span>r<span class="sc">:1.4e}</span><span class="ss"> m'</span>)</span>
<span id="cb18-6"><a href="#cb18-6"></a><span class="bu">print</span>(<span class="ss">f'Conventional flux for zero apparent magnitude (m=0): F0=</span><span class="sc">{</span>f0<span class="sc">:1.4e}</span><span class="ss"> W/m/m'</span>)</span>
<span id="cb18-7"><a href="#cb18-7"></a><span class="bu">print</span>(<span class="ss">f'Conventional luminosity for zero absolute magnitude (M=0): L0=</span><span class="sc">{</span>L0<span class="sc">:1.4e}</span><span class="ss"> W'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>r = 10 pc = 3.0857e+17 m
Conventional flux for zero apparent magnitude (m=0): F0=2.5180e-08 W/m/m
Conventional luminosity for zero absolute magnitude (M=0): L0=3.0128e+28 W</code></pre>
</div>
</div>
<p>The zero value of the absolute magnitude, <span class="math inline">\(M=0\)</span>, corresponds to a luminosity of</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zero point luminosity (conventional)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-zero-point-luminosity"><span class="math display">\[
L_0 = 4\pi r^2 F_0 = 3.0128 \times 10^{28} \mathrm{W}.
\tag{1.10}\]</span></span> (Reference: <a href="https://www.iau.org/static/resolutions/IAU2015_English.pdf">IAU 2015 resolution.</a>)</p>
</div>
</div>
<p>Plugging <a href="#eq-flux">Equation&nbsp;<span>1.1</span></a> into <a href="#eq-apparent-magnitude-convention">Equation&nbsp;<span>1.6</span></a>, and considering that by definition the absolute magnitude is equal to the apparent magnitude at a distance <span class="math inline">\(r=10\mathrm{pc}\)</span>, we can define the absolute magnitude as</p>
<div class="callout callout-style-default callout-note callout-titled" style="simple">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Absolute magnitude (conventional)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-absolute-mangitude-convention"><span class="math display">\[
M = -2.5 \log_{10}{\frac{L}{L_0}} = -2.5\log_{10} L + 71.1974.
\tag{1.11}\]</span></span></p>
</div>
</div>
<p>Using this convention, the absolute magnitude of the Sun, having a <em>nominal solar luminosity</em> <span class="math inline">\(L_\odot = 3.828 \times 10^{26} \mathrm{W}\)</span>, is <span id="eq-sun-absolute-magnitude"><span class="math display">\[
M_\odot = 4.74\mathrm{mag}.
\tag{1.12}\]</span></span></p>
<div class="cell" data-execution_count="9">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1"></a><span class="im">from</span> numpy <span class="im">import</span> log10</span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="im">from</span> astropy.constants <span class="im">import</span> L_sun, L_bol0</span>
<span id="cb20-3"><a href="#cb20-3"></a></span>
<span id="cb20-4"><a href="#cb20-4"></a><span class="bu">print</span>(L_sun)</span>
<span id="cb20-5"><a href="#cb20-5"></a><span class="bu">print</span>(L_bol0)</span>
<span id="cb20-6"><a href="#cb20-6"></a>L0 <span class="op">=</span> <span class="fl">3.0128E28</span> <span class="co"># W</span></span>
<span id="cb20-7"><a href="#cb20-7"></a>M <span class="op">=</span> <span class="op">-</span><span class="fl">2.5</span><span class="op">*</span>log10(L_sun<span class="op">/</span>L_bol0)</span>
<span id="cb20-8"><a href="#cb20-8"></a><span class="bu">print</span>(<span class="ss">f'Absolute magnitude of the Sun: M_sun = </span><span class="sc">{</span>M<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Name   = Nominal solar luminosity
  Value  = 3.828e+26
  Uncertainty  = 0.0
  Unit  = W
  Reference = IAU 2015 Resolution B 3
  Name   = Luminosity for absolute bolometric magnitude 0
  Value  = 3.0128e+28
  Uncertainty  = 0.0
  Unit  = W
  Reference = IAU 2015 Resolution B 2
Absolute magnitude of the Sun: M_sun = 4.74</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>In different textbooks or sources (not updated to the IAU 2015 resolution), you may find different conventions for the zero points of apparent and absolute magnitudes. Consequently, you may have different values of the apparent and absolute magnitudes of the Sun (or other stars). For example, you may find that in some books the solar absolute bolometric magnitude is <span class="math inline">\(M_\odot=4.83\)</span> instead of <span class="math inline">\(M_\odot=4.74\)</span>.</p>
</div>
</div>
</section>
</section>
<section id="setting-the-absolute-magnitude-scale" class="level3" data-number="1.5.6">
<h3 data-number="1.5.6" class="anchored" data-anchor-id="setting-the-absolute-magnitude-scale"><span class="header-section-number">1.5.6</span> Setting the Absolute Magnitude scale</h3>
<p>We will need to convert magnitudes to S.I. units of luminosity. <!-- __Updated convention__ --></p>
<p>Based on the <a link="https://www.iau.org/static/resolutions/IAU2015_English.pdf"> IAU 2015 resolution</a>, we use the zero point luminosity previously introduced in <a href="#eq-zero-point-luminosity">Equation&nbsp;<span>1.10</span></a> (<span class="math inline">\(L_0=3.0128\times 10^{28}\)</span> W) to define the absolute magnitude in <a href="#eq-absolute-mangitude-convention">Equation&nbsp;<span>1.11</span></a>. Rearranging this, we find that for a star with absolute magnitude <span class="math inline">\(M\)</span>, the luminosity is given by <span id="eq-absolute-magnitude-scale"><span class="math display">\[
L = L_0 10^{-0.4 M}.
\tag{1.13}\]</span></span></p>
<p>You may notice that this definition uses only the zero point value of the luminosity defined in <a href="#eq-zero-point-luminosity">Equation&nbsp;<span>1.10</span></a> to relate the luminosity and absolute magnitude of a star.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Once again, some caution is needed when consulting textbooks and other sources, as conventions may change. Other (outdated) sources may use other references for the absolute magnitude <span class="math inline">\(M_2\)</span> of <a href="#eq-absolute-magnitude">Equation&nbsp;<span>1.9</span></a> instead of the zero value used in <a href="#eq-absolute-mangitude-convention">Equation&nbsp;<span>1.11</span></a> and in the derivation above. In some cases for instance you may find that the solar absolute magnitude is used: <span class="math inline">\(M_2=M_{\odot}=4.74\)</span> (remember that even this value can change depending on the convention used, see ‘caution’ callout above.)</p>
</div>
</div>
<!-- __Outdated convention__ -->
<!-- Some textbooks use the following (outdated) convention, illustrated here for completeness:
- consider the absolute magnitude definition of @eq-absolute-magnitude and take the Sun as a reference, with absolute magnitude $M_2=M_{\odot}=4.74$ (remember that even this value can change depending on the convention used, see 'caution' callout above. In the older convention $M_{\odot}=4.83$.)
- therefore, for a star with luminosity $L$ the absolute magnitude $M$ is given by
$$
M=-2.5\log_{10}L+2.5\log_{10}L_\odot + 4.74.
$${#eq-absolute-magnitude-scale-obsolete}
- this can be rearranged to find the the luminosity of a star with absolute magnitude $M$:
$$
L=L_\odot 10^{4.74 - M}.
$$
This older convention uses the solar absolute magnitude as a reference. -->
</section>
<section id="example" class="level3" data-number="1.5.7">
<h3 data-number="1.5.7" class="anchored" data-anchor-id="example"><span class="header-section-number">1.5.7</span> <span style="color:#336699;">Example</span></h3>
<p>We can use this formula to recover the luminosity of the Sun previously used (<span class="math inline">\(L_\odot = 3.826 \times 10^{26}\mathrm{W}\)</span>), having the absolute magnitude of the Sun, <span class="math inline">\(M_\odot = 4.74\)</span>.</p>
<div class="cell" data-execution_count="10">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1"></a><span class="im">from</span> astropy.constants <span class="im">import</span> L_bol0</span>
<span id="cb22-2"><a href="#cb22-2"></a></span>
<span id="cb22-3"><a href="#cb22-3"></a>M_sun <span class="op">=</span> <span class="fl">4.74</span></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="bu">print</span>(L_bol0)</span>
<span id="cb22-5"><a href="#cb22-5"></a>L <span class="op">=</span> L_bol0<span class="op">*</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="fl">0.4</span><span class="op">*</span>M_sun)</span>
<span id="cb22-6"><a href="#cb22-6"></a><span class="bu">print</span>(<span class="ss">f'Luminosity of the Sun: L = </span><span class="sc">{</span>L<span class="sc">:1.3e}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Name   = Luminosity for absolute bolometric magnitude 0
  Value  = 3.0128e+28
  Uncertainty  = 0.0
  Unit  = W
  Reference = IAU 2015 Resolution B 2
Luminosity of the Sun: L = 3.828e+26 W</code></pre>
</div>
</div>
</section>
<section id="question-2" class="level3" data-number="1.5.8">
<h3 data-number="1.5.8" class="anchored" data-anchor-id="question-2"><span class="header-section-number">1.5.8</span> <span style="color:#336699;">Question</span></h3>
<p>Show that if we have two stars with luminosities (units <span class="math inline">\(W\)</span>) <span class="math inline">\(L_1\)</span> and <span class="math inline">\(L_2\)</span> at the same distance <span class="math inline">\(r=10\mathrm{pc}\)</span>, their difference in the apparent magnitudes is the same as the difference of the absolute magnitudes:</p>
<p><span class="math display">\[
\begin{aligned}
M_1 - M_2 = -2.5 \log_{10} \frac{L_1}{L_2}
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use the relationship between flux and luminosity and the properties of logarithms.</p>
</div>
</div>
</div>
<details>
<summary>
Solution
</summary>
<p>For two stars <em>at the same distance</em> <span class="math inline">\(r\)</span> (e.g.&nbsp;two stars in a binary), we can write</p>
<p><span class="math display">\[
\begin{aligned}
m_1 - m_2 &amp;= -2.5\log_{10}\left(\frac{L_1}{4\pi r^2} \times \frac{4\pi r^2}{L_2} \right)\\
&amp;= -2.5\log_{10}\frac{L_1}{L_2}
\end{aligned}
\]</span></p>
<p>Having defined the absolute magnitude using the zero point flux above, for the i-th star (i.e.&nbsp;for i=1,2) with luminosities <span class="math inline">\(L_i\)</span> at distances of 10pc, the absolute magnitude is: <span class="math inline">\(M_i = -2.5 \log_{10}{\dfrac{L_i}{L_0}}\)</span></p>
<p>Therefore: <span class="math display">\[
\begin{aligned}
M_1 - M_2 &amp; = -2.5 \log_{10}{\frac{L_1}{L_0}} - \left(-2.5 \log_{10}{\frac{L_2}{L_0}}\right) \\
&amp; = -2.5\log_{10} L_1 +2.5\log_{10} L_0 + 2.5\log_{10} L_2 - 2.5\log_{10} L_0 \\
&amp; = -2.5 \log_{10} L_1 + 2.5 \log_{10} L_2\\
&amp; = -2.5 \log_{10}{\frac{L_1}{L_2}}
\end{aligned}
\]</span></p>
<ul>
<li>For two stars at the same distance of 10pc from the observer, the difference in the apparent magnitude is equal to the difference in the absolute magnitude.</li>
</ul>
</details></section>
<section id="relationship-between-apparent-magnitude-and-absolute-magnitude" class="level3" data-number="1.5.9">
<h3 data-number="1.5.9" class="anchored" data-anchor-id="relationship-between-apparent-magnitude-and-absolute-magnitude"><span class="header-section-number">1.5.9</span> Relationship between apparent magnitude and absolute magnitude</h3>
<p>By using the conventional definitions of the apparent magnitude and absolute magnitude, we can find the relationship between them:</p>
<p><span class="math display">\[
\begin{aligned}
m &amp;= -2.5\log_{10}{\frac{F}{F_0}} \\
&amp;= -2.5\log_{10}\left(\frac{L}{4\pi r^2}\times \frac{4\pi (10\mathrm{pc})^2}{L_0} \right) \\
&amp; =-2.5\log_{10}\left(\frac{L}{L_0}\right) -2.5\log_{10} \left( \frac{10\mathrm{pc}}{r}\right)^2\\
&amp; = M -5\log_{10}(10\mathrm{pc})+5\log_{10}{r}\\
&amp; = M -5 + 5\log_{10}{r}.
\end{aligned}
\]</span> Then <span id="eq-apparent-absolute-magnitude"><span class="math display">\[
M = m + 5 - 5\log_{10} r.
\tag{1.14}\]</span></span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Careful to the units in <a href="#eq-apparent-absolute-magnitude">Equation&nbsp;<span>1.14</span></a>! Here <span class="math inline">\(r\)</span> is measured in <strong>parsecs</strong>. Use this formula with caution!</p>
</div>
</div>
<!-- ## 5.3. <a id='toc5_3_'></a>[Apparent magnitude and luminosity](#toc0_)

If the two objects are at the same distance $r$ (e.g. two stars in a binary) then we can write

$$
\begin{aligned}
m_1 - m_2 &= -2.5\log_{10}\left(\frac{L_1}{4\pi r^2} \times \frac{4\pi r^2}{L_2} \right)\\
&= -2.5\log_{10}\frac{L_1}{L_2}
\end{aligned}
$$ -->
<!-- ## 5.4. <a id='toc5_4_'></a>[Absolute magnitude and luminosity](#toc0_)
Remember that the absolute magnitude $M$ is equal to the apparent magnitude $m$ at 10 pc distance.

Mathematically, using the relationship between apparent and absolute magnitudes: $M = m +5 -5\log_{10}r$, it follows that

$$
\begin{aligned}
M_1 - M_2 = -2.5 \log_{10}\frac{L_1}{L_2}
\end{aligned}
$$ -->
</section>
<section id="magnitudes-luminosity-and-distance" class="level3" data-number="1.5.10">
<h3 data-number="1.5.10" class="anchored" data-anchor-id="magnitudes-luminosity-and-distance"><span class="header-section-number">1.5.10</span> Magnitudes, luminosity and distance</h3>
<ul>
<li>If you know a star’s apparent magnitude <span class="math inline">\(m\)</span> and know its absolute magnitude <span class="math inline">\(M\)</span> you can calculate its distance <span class="math inline">\(r\)</span> (in parsec!) using <span class="math inline">\(M=m + 5 - 5\log_{10} r\)</span>.</li>
<li>If you know a star’s apparent magnitude and distance you can compute its luminosity</li>
<li>You should practice this type of conversion!</li>
</ul>
</section>
<section id="example-1" class="level3" data-number="1.5.11">
<h3 data-number="1.5.11" class="anchored" data-anchor-id="example-1"><span class="header-section-number">1.5.11</span> <span style="color:#336699;">Example</span></h3>
<p>A star with apparent magnitude <span class="math inline">\(4.2\)</span> is measured by parallax to have a distance of <span class="math inline">\(20\)</span> parsecs. What is the absolute magnitude?</p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;notes&quot;}" data-execution_count="11">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1"></a><span class="im">from</span> numpy <span class="im">import</span> log10</span>
<span id="cb24-2"><a href="#cb24-2"></a>m<span class="op">=</span><span class="fl">4.2</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>r<span class="op">=</span><span class="dv">20</span> <span class="co">#pc</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>M <span class="op">=</span> m <span class="op">+</span> <span class="dv">5</span> <span class="op">-</span> <span class="dv">5</span><span class="op">*</span>log10(r)</span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="bu">print</span>(<span class="ss">f'M = m + 5 - 5*log10(r) = </span><span class="sc">{</span>m<span class="sc">}</span><span class="ss"> + 5 - log10(</span><span class="sc">{</span>r<span class="sc">:.2f}</span><span class="ss">)=</span><span class="sc">{</span>m<span class="sc">}</span><span class="ss">+5</span><span class="sc">{</span><span class="op">-</span>log10(r)<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>M<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="bu">print</span>(<span class="ss">f'Absolute magnitude is </span><span class="sc">{</span>M<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>M = m + 5 - 5*log10(r) = 4.2 + 5 - log10(20.00)=4.2+5-1.3010299956639813 = 2.694850021680093
Absolute magnitude is 2.69</code></pre>
</div>
</div>
</section>
<section id="notes-on-types-of-magnitude" class="level3" data-number="1.5.12">
<h3 data-number="1.5.12" class="anchored" data-anchor-id="notes-on-types-of-magnitude"><span class="header-section-number">1.5.12</span> Notes on types of magnitude</h3>
<p>The magnitude observed can depend on the sensitivity of the telescope or detector to the range of wavelengths. For instance, the human eye can observe in the visible part of the spectrum, but not in the IR or UV. Likewise, telescopes can have filters to observe different parts of the spectrum. Magnitude can therefore be specified for different wavelength intervals, i.e.&nbsp;observed with different coloured filters on the telescope.</p>
<ul>
<li>For stars, the most commonly quoted magnitude is the <strong>visual magnitude</strong>, the magnitude in the visual part of the spectrum.</li>
<li>Another commonly used magnitude is the <strong>bolometric magnitude</strong>, which include the luminosity across the whole electromagnetic spectrum of wavelengths, whether observed or not. We will use this when performing some physics calculations.</li>
<li>One of the most common magnitude systems used in photometry is the <strong>UBV system</strong>, where magnitudes are measured through ultraviolet (U), blue (B) and visual (V) filters.</li>
</ul>
<p>The magnitudes we mentioned so far, e.g.&nbsp;<span class="math inline">\(M_\odot = 4.74\)</span>, are <strong>bolometric magnitudes</strong>.</p>
<p>The visual magnitude <span class="math inline">\(V\)</span> and the bolometric magnitude <span class="math inline">\(M_{bol}\)</span> (or just <span class="math inline">\(M\)</span>) are related by the <em>bolometric correction</em> BC through the formula</p>
<p><span id="eq-bolometric-correction"><span class="math display">\[
M_{bol} - V = BC,
\tag{1.15}\]</span></span></p>
<p>where <span class="math inline">\(BC&lt;0\)</span>.</p>
<p>In a multicolour system, such as UBV, it is useful to introduce the <strong>colour index</strong>. This is the difference between two magnitudes of that system. Considering the UBV system, for instance:</p>
<ul>
<li>the <span class="math inline">\(U-B\)</span> color index of a star is the difference between its ultraviolet and blue magnitudes (<span class="math inline">\(U-B=M_U-M_B\)</span>)</li>
<li>the <span class="math inline">\(B-V\)</span> color index of a star is the difference between its blue and visual magnitudes (<span class="math inline">\(V-B=M_V-M_B\)</span>).</li>
</ul>
<p>We will come back to this again in the next chapter.</p>
</section>
</section>
<section id="recap" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="recap"><span class="header-section-number">1.6</span> Recap</h2>
<ul>
<li><p>The distance to near stars can be determined using the parallax method</p></li>
<li><p>1 parsec is the distance to a star having a parallax angle of 1 arcsec</p></li>
<li><p>The apparent brightness of a star scales with the inverse square of the distance to the star</p></li>
<li><p>The luminosity of a star is the total energy emitted per unit time</p></li>
<li><p>The magnitude scale is logarithmic</p></li>
<li><p>Apparent magnitude is a measure of brightness dependent on the distance to the observer</p></li>
<li><p>Absolute magnitude is a measure of brightness intrinsic to the star</p></li>
<li><p>We can find the luminosity in S.I. units from the absolute magnitude</p></li>
<li><p>We can convert apparent to absolute magnitude if we know the distance to the star in parsecs</p></li>
</ul>
</section>
<section id="stellar-colour" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="stellar-colour"><span class="header-section-number">1.7</span> Stellar Colour</h2>
<section id="why-are-the-stars-different-colours" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="why-are-the-stars-different-colours"><span class="header-section-number">1.7.1</span> Why are the stars different colours?</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/intro2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Stars of different colours</figcaption>
</figure>
</div>
<p>We anticipated that stars have different colours in the first section of this chapter (see <a href="#fig-Stellarium-stars-compare">Figure&nbsp;<span>1.3</span></a>), where we introduced the observed properties of stars.</p>
<p>Why are stars different colours?</p>
<p>We know that light is an electromagnetic wave, and that the colour we perceive depends on the wavelength of the light.</p>
<div id="fig-visible-spectrum" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/Linear_visible_spectrum.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.16: Linear representation of the visible light spectrum. Credits: <a href="https://upload.wikimedia.org/wikipedia/commons/d/d9/Linear_visible_spectrum.svg">Wikimedia</a></figcaption>
</figure>
</div>
<ul>
<li>Red light has a wavelength <span class="math inline">\(\approx 650\)</span> nm</li>
<li>Blue light has a wavelength <span class="math inline">\(\approx 450\)</span> nm</li>
<li>White light is a mixture of all visible wavelengths</li>
</ul>
<p>The reason why stars appear to have different colours is that they do not emit the same amount of radiation at all wavelengths: some star emit more toward the red end of the spectrum, others toward the blue end, as well as beyond the visible window, such as emission in the infrared or ultraviolet.</p>
<p>To understand what regulates the emission of stars at the different wavelengths, determining the colours that we observe, we need to introduce the concept of <em>black-body</em>.</p>
</section>
<section id="black-body-radiation" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="black-body-radiation"><span class="header-section-number">1.7.2</span> Black body radiation</h3>
<ul>
<li>A body that totally absorbs all radiation that falls upon it is called a <strong>black-body</strong>. You can think of it as a perfect absorber of radiation.</li>
<li>A black body is in thermal equilibrium, so it has a temperature <span class="math inline">\(T\)</span>.</li>
<li>If it absorbs energy then it must also re-radiate it to stay in thermal equilibrium.</li>
<li>A black body is a perfect absorber but it is also a perfect emitter.</li>
</ul>
<p>We anticipated that stars radiate different amounts of energy at different wavelengths. Let us assume that we can consider stars as black bodies.</p>
<p>What is the distribution of radiation across wavelengths (or frequencies) that a black body emits?</p>
<!-- Earlier in this chapter we defined the _radiant flux_ (@eq-flux) as the energy received per second, per unit area. -->
<p>We want to know the power emitted per unit wavelength <span class="math inline">\(\lambda\)</span>, per unit area, per unit solid angle (steradian): the <strong>spectral radiance</strong> <span class="math inline">\(B_\lambda(\lambda;T)\)</span>.</p>
<p>For a perfect emitter, radiation is emitted:</p>
<ul>
<li><em>equally</em> from the surface of an object</li>
<li><em>isotropically</em> over solid angle.</li>
</ul>
<p><em>The emission spectra of black bodies (the energy emitted against the wavelength or frequency) depend only on their temperature <span class="math inline">\(T\)</span>.</em></p>
<p>So what is the form of the emission spectrum of a black body? Although the spectrum of black-body radiation was known observationally, its theoretical description has puzzled physicists at the end of the 19th Century and many attempts to describe this ran into trouble. It cannot be fully explained using classical physics, it requires quantum physics, as we will see in the following.</p>
<section id="rayleigh-jeans-law" class="level4" data-number="1.7.2.1">
<h4 data-number="1.7.2.1" class="anchored" data-anchor-id="rayleigh-jeans-law"><span class="header-section-number">1.7.2.1</span> Rayleigh-Jeans law</h4>
<p>Lord Rayleigh used classical physics to predict the shape of the black body spectrum, which was later refined by Sir James Jeans.</p>
<p>The Rayleigh-Jeans law is a good approximation to the observed spectrum at long wavelength (low frequencies) <span class="math inline">\(hc\ll k_BT\lambda\)</span>.</p>
<p><span id="eq-rayleigh-jeans-law"><span class="math display">\[
B_\lambda^\mathrm{RJ}(\lambda; T) = \frac{2ck_B T}{\lambda^4}
\tag{1.16}\]</span></span></p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/strutt.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Lord Rayleigh (1842 - 1918)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/James_Hopwood_Jeans.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Sir James Jeans (1877 - 1946)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;skip&quot;}" data-execution_count="12">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1"></a><span class="im">import</span> warnings</span>
<span id="cb26-2"><a href="#cb26-2"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="im">from</span> astropy.constants <span class="im">import</span> k_B, c, h</span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="im">from</span> matplotlib <span class="im">import</span> rc</span>
<span id="cb26-7"><a href="#cb26-7"></a>rc(<span class="st">'text'</span>,usetex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-8"><a href="#cb26-8"></a>rc(<span class="st">'font'</span>,size<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb26-9"><a href="#cb26-9"></a>rc(<span class="st">'figure'</span>,figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">6</span>), dpi<span class="op">=</span><span class="dv">300</span>)</span>
<span id="cb26-10"><a href="#cb26-10"></a></span>
<span id="cb26-11"><a href="#cb26-11"></a>l <span class="op">=</span> np.linspace(<span class="dv">0</span>,<span class="dv">3000</span>,<span class="dv">1000</span>) <span class="co"># Wavelength, nm</span></span>
<span id="cb26-12"><a href="#cb26-12"></a>T <span class="op">=</span> <span class="dv">4000</span> <span class="co"># Temperature, Kelvin</span></span>
<span id="cb26-13"><a href="#cb26-13"></a></span>
<span id="cb26-14"><a href="#cb26-14"></a>B_rj<span class="op">=</span>c.value<span class="op">*</span> <span class="dv">2</span><span class="op">*</span>k_B.value <span class="op">*</span> T <span class="op">/</span>(l<span class="op">*</span><span class="fl">1e-9</span>)<span class="op">**</span><span class="dv">4</span><span class="op">;</span> <span class="co"># 1e-9 to convert from nm to meters</span></span>
<span id="cb26-15"><a href="#cb26-15"></a></span>
<span id="cb26-16"><a href="#cb26-16"></a>plt.plot(l, B_rj, label<span class="op">=</span><span class="st">"Rayleigh-Jeans law"</span>)</span>
<span id="cb26-17"><a href="#cb26-17"></a>plt.xlabel(<span class="vs">r'Wavelength $\lambda$ (nm)'</span>)</span>
<span id="cb26-18"><a href="#cb26-18"></a>plt.ylabel(<span class="vs">r'Spectral Radiance $B_\lambda(\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)'</span>)</span>
<span id="cb26-19"><a href="#cb26-19"></a>plt.title(<span class="st">'Spectral radiance'</span>)</span>
<span id="cb26-20"><a href="#cb26-20"></a>plt.ylim([<span class="dv">0</span>,<span class="fl">1e15</span>])</span>
<span id="cb26-21"><a href="#cb26-21"></a>plt.grid()</span>
<span id="cb26-22"><a href="#cb26-22"></a>plt.legend()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-rayleigh-jeans-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-jeans-plot-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.17: Spectral radiance plotted using the Rayleigh-Jeans law (<a href="#eq-rayleigh-jeans-law">Equation&nbsp;<span>1.16</span></a>).</figcaption>
</figure>
</div>
</div>
</div>
<p>The Rayleigh-Jeans law has a big problem - the radiance keeps increasing indefinitely at short wavelengths (higher frequencies). If it were true the power emitted at short wavelengths would be infinite! This is known as the <em>Ultraviolet Catastrophe</em>, and indicates the failure of classical physics to explain the behaviour of thermal radiation.</p>
</section>
<section id="wiens-approximation" class="level4" data-number="1.7.2.2">
<h4 data-number="1.7.2.2" class="anchored" data-anchor-id="wiens-approximation"><span class="header-section-number">1.7.2.2</span> Wien’s approximation</h4>
<p>Wien’s approximation, also referred to as Wien’s law (not to be confused with ‘Wien’s displacement law’), is a good model for the observed spectrum at short wavelength (high frequencies) <span class="math inline">\(hc\gg k_BT\lambda\)</span>, but it is not accurate at high wavelengths. Wien’s approximation is described by the form below.</p>
<p><span id="eq-Wien_approx"><span class="math display">\[
B_\lambda^\mathrm{Wien}(\lambda; T) = \frac{2 hc^2}{\lambda^5}\exp\left(-\frac{hc}{\lambda k_B T}\right)
\tag{1.17}\]</span></span></p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;skip&quot;}" data-execution_count="13">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1"></a>B_wien<span class="op">=</span><span class="dv">2</span> <span class="op">*</span> h.value <span class="op">*</span>c.value<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> np.exp(<span class="op">-</span>h.value<span class="op">*</span>c.value<span class="op">/</span>((l<span class="op">*</span><span class="fl">1e-9</span>)<span class="op">*</span>k_B.value<span class="op">*</span>T)) <span class="op">/</span> (l<span class="op">*</span><span class="fl">1e-9</span>)<span class="op">**</span><span class="dv">5</span><span class="op">;</span></span>
<span id="cb27-2"><a href="#cb27-2"></a></span>
<span id="cb27-3"><a href="#cb27-3"></a>plt.plot(l, B_rj, label<span class="op">=</span><span class="st">"Rayleigh-Jeans law"</span>)</span>
<span id="cb27-4"><a href="#cb27-4"></a>plt.plot(l, B_wien, label<span class="op">=</span><span class="st">"Wien's approximation"</span>)</span>
<span id="cb27-5"><a href="#cb27-5"></a></span>
<span id="cb27-6"><a href="#cb27-6"></a>plt.xlabel(<span class="vs">r'Wavelength $\lambda$ (nm)'</span>)</span>
<span id="cb27-7"><a href="#cb27-7"></a>plt.ylabel(<span class="vs">r'Spectral Radiance $B_\lambda(\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)'</span>)</span>
<span id="cb27-8"><a href="#cb27-8"></a>plt.title(<span class="st">'Spectral radiance'</span>)</span>
<span id="cb27-9"><a href="#cb27-9"></a>plt.ylim([<span class="dv">0</span>,<span class="fl">5e12</span>])</span>
<span id="cb27-10"><a href="#cb27-10"></a>plt.grid()</span>
<span id="cb27-11"><a href="#cb27-11"></a>plt.legend()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-rayleigh-wien-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-wien-plot-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.18: Comparison of the spectral radiance plotted using the Rayleigh-Jeans law (<a href="#eq-rayleigh-jeans-law">Equation&nbsp;<span>1.16</span></a>) and the Wien’s approximation (<a href="#eq-Wien_approx">Equation&nbsp;<span>1.17</span></a>).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="plancks-law" class="level4" data-number="1.7.2.3">
<h4 data-number="1.7.2.3" class="anchored" data-anchor-id="plancks-law"><span class="header-section-number">1.7.2.3</span> Planck’s Law</h4>
<p>In 1900 Planck was able to derive a spectrum that fit the data by assuming that energy comes in discrete quanta of energy <span class="math inline">\(E = h\nu = hc/\lambda\)</span>, with <span class="math inline">\(h\)</span> being a constant, Planck constant. This marked the birth of quantum physics! The Planck radiation spectrum for a black body’s spectral radiance is:</p>
<p><span id="eq-planck-law"><span class="math display">\[
B_\lambda(\lambda; T) = \frac{2 hc^2}{\lambda^5}\left(\frac{1}{\exp\left(\frac{hc}{\lambda k_B T}\right) -1} \right)
\tag{1.18}\]</span></span></p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;subslide&quot;}" data-execution_count="14">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1"></a>B_planck <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>h.value<span class="op">*</span>c.value<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> (<span class="fl">1.0</span><span class="op">/</span>(np.exp(h.value<span class="op">*</span>c.value<span class="op">/</span>(k_B.value<span class="op">*</span>T<span class="op">*</span>(l<span class="op">*</span><span class="fl">1e-9</span>)))<span class="op">-</span><span class="dv">1</span>)) <span class="op">/</span> (l<span class="op">*</span><span class="fl">1e-9</span>)<span class="op">**</span><span class="dv">5</span><span class="op">;</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>plt.plot(l, B_planck, label<span class="op">=</span><span class="st">"Planck's law"</span>)</span>
<span id="cb28-3"><a href="#cb28-3"></a>plt.plot(l, B_wien, label<span class="op">=</span><span class="st">"Wien's approximation"</span>)</span>
<span id="cb28-4"><a href="#cb28-4"></a>plt.plot(l, B_rj, label<span class="op">=</span><span class="st">"Rayleigh-Jeans law"</span>)</span>
<span id="cb28-5"><a href="#cb28-5"></a></span>
<span id="cb28-6"><a href="#cb28-6"></a>plt.xlabel(<span class="vs">r'Wavelength $\lambda$ (nm)'</span>)</span>
<span id="cb28-7"><a href="#cb28-7"></a>plt.ylabel(<span class="vs">r'Spectral Radiance $B_\lambda(\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)'</span>)</span>
<span id="cb28-8"><a href="#cb28-8"></a>plt.title(<span class="st">'Spectral radiance'</span>)</span>
<span id="cb28-9"><a href="#cb28-9"></a>plt.ylim([<span class="dv">0</span>,<span class="fl">5e12</span>])</span>
<span id="cb28-10"><a href="#cb28-10"></a>plt.grid()</span>
<span id="cb28-11"><a href="#cb28-11"></a>plt.legend()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-rayleigh-wien-planck-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="SP1.1_-_Stellar_Properties_files/figure-html/fig-rayleigh-wien-planck-plot-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.19: Comparison of the spectral radiance plotted using the Rayleigh-Jeans law (<a href="#eq-rayleigh-jeans-law">Equation&nbsp;<span>1.16</span></a>), Wien’s approximation (<a href="#eq-Wien_approx">Equation&nbsp;<span>1.17</span></a>) and Planck’s law (<a href="#eq-planck-law">Equation&nbsp;<span>1.18</span></a>)</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="exercise" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="exercise"><span class="header-section-number">1.7.3</span> <span style="color:#336699;">Exercise</span></h3>
<ol type="1">
<li>Show that for low frequencies (<span class="math inline">\(hc \ll \lambda k_B T\)</span>) the Rayleigh-Jeans law can be derived from the Planck law.</li>
<li>Show that for high frequencies (<span class="math inline">\(hc \gg \lambda k_B T\)</span>) Wien’s law can be derived from the Planck law.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can use the approximation <span class="math inline">\(\lim_{x\rightarrow 0} \exp(x) = 1 + x\)</span></p>
</div>
</div>
</div>
</section>
</section>
<section id="temperature-and-colour" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="temperature-and-colour"><span class="header-section-number">1.8</span> Temperature and colour</h2>
<p>Let’s look at how the spectrum changes with temperature <span class="math inline">\(T\)</span>.</p>
<p>We can try out this <a href="https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum_en.html">PhET interactive simulator</a> and by varying the temperature we can see how the black body spectrum changes.</p>
<p>The change of the spectral radiance with temperature is shown in <a href="#fig-spectral-radiance-vs-temp">Figure&nbsp;<span>1.20</span></a>.</p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;subslide&quot;}" data-execution_count="15">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1"></a><span class="im">import</span> warnings</span>
<span id="cb29-2"><a href="#cb29-2"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb29-3"><a href="#cb29-3"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb29-4"><a href="#cb29-4"></a></span>
<span id="cb29-5"><a href="#cb29-5"></a><span class="cf">for</span> T <span class="kw">in</span> [<span class="dv">6000</span>,<span class="dv">5500</span>,<span class="dv">5000</span>,<span class="dv">4500</span>,<span class="dv">4000</span>]:</span>
<span id="cb29-6"><a href="#cb29-6"></a>    B_planck <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>h.value<span class="op">*</span>c.value<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> (<span class="fl">1.0</span><span class="op">/</span>(np.exp(h.value<span class="op">*</span>c.value<span class="op">/</span>(k_B.value<span class="op">*</span>T<span class="op">*</span>(l<span class="op">*</span><span class="fl">1e-9</span>)))<span class="op">-</span><span class="dv">1</span>)) <span class="op">/</span> (l<span class="op">*</span><span class="fl">1e-9</span>)<span class="op">**</span><span class="dv">5</span></span>
<span id="cb29-7"><a href="#cb29-7"></a>    plt.plot(l, B_planck, label<span class="op">=</span><span class="st">'T='</span><span class="op">+</span><span class="bu">str</span>(T)<span class="op">+</span><span class="st">'K'</span>)</span>
<span id="cb29-8"><a href="#cb29-8"></a></span>
<span id="cb29-9"><a href="#cb29-9"></a></span>
<span id="cb29-10"><a href="#cb29-10"></a>plt.xlabel(<span class="vs">r'Wavelength $\lambda$ (nm)'</span>)</span>
<span id="cb29-11"><a href="#cb29-11"></a>plt.ylabel(<span class="vs">r'Spectral Radiance $B_\lambda(\lambda, T=4000K)$ (Wm$^{-3}$sr$^{-1}$)'</span>)</span>
<span id="cb29-12"><a href="#cb29-12"></a>plt.title(<span class="st">'Spectral radiance at different temperatures'</span>)</span>
<span id="cb29-13"><a href="#cb29-13"></a>plt.grid()</span>
<span id="cb29-14"><a href="#cb29-14"></a>plt.legend()</span>
<span id="cb29-15"><a href="#cb29-15"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-spectral-radiance-vs-temp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="SP1.1_-_Stellar_Properties_files/figure-html/fig-spectral-radiance-vs-temp-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.20: Spectral radiance at different temperatures.</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-spectral-radiance-vs-temp">Figure&nbsp;<span>1.20</span></a> we notice that the Planck spectrum:</p>
<ul>
<li>has a clear peak at some wavelength, which decreases as temperature increases</li>
<li><span class="math inline">\(B_\lambda(\lambda;T)&gt; 0\)</span> for all wavelengths, but tends toward <span class="math inline">\(0\)</span> at the extreme ends of the spectrum</li>
<li>overall increases with temperature</li>
</ul>
<p>Black bodies radiate at all wavelengths - they won’t look black! The shape of the spectrum and the position of the peak determine the apparent colour of the object.</p>
<section id="wiens-displacement-law" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="wiens-displacement-law"><span class="header-section-number">1.8.1</span> Wien’s displacement law</h3>
<p>There is an inverse relationship between the temperature <span class="math inline">\(T\)</span> in Kelvin and the peak emission wavelength <span class="math inline">\(\lambda_{peak}\)</span> in metres, called <em>Wien’s displacement law</em>: <span id="eq-wien-displacement-law"><span class="math display">\[
\lambda_{peak} = \frac{0.0029\,\mathrm{m\,K}}{T}
\tag{1.19}\]</span></span></p>
<p>Here <span class="math inline">\(\mathrm{m\,K}\)</span> are metres <span class="math inline">\(\times\)</span> kelvin, the units of the constant.</p>
<p>Note that this is different from Wien’s law, or Wien’s approximation, encountered earlier (<a href="#eq-Wien_approx">Equation&nbsp;<span>1.17</span></a>).</p>
<p>We can use Wien’s displacement law to determine the effective temperature of a star from the spectrum of its light, assuming it is a black body.</p>
</section>
<section id="question-3" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="question-3"><span class="header-section-number">1.8.2</span> <span style="color:#336699;">Question</span></h3>
<p>The Sun’s spectrum has a peak wavelength of around 500 nm, in the green part of the spectrum (see <a href="#fig-solar-irradiance">Figure&nbsp;<span>1.21</span></a>). What is the effective emission temperature of the Sun?</p>
<div id="fig-solar-irradiance" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/solar_irradiance.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.21: Spectrum of Solar Radiation as seen from Earth and from above Earth’s atmosphere, and fitting of the black-body curve.</figcaption>
</figure>
</div>
<details>
<summary>
Solution
</summary>
<p>We can use <a href="#eq-wien-displacement-law">Equation&nbsp;<span>1.19</span></a>, after converting the peak wavelength from nm to m.</p>
<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;notes&quot;}" data-execution_count="16">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1"></a>w <span class="op">=</span> <span class="fl">0.0029</span> <span class="co"># constant in m K</span></span>
<span id="cb30-2"><a href="#cb30-2"></a>lmax <span class="op">=</span> <span class="fl">500e-9</span> <span class="co"># peak wavelength in metres</span></span>
<span id="cb30-3"><a href="#cb30-3"></a>Tsun <span class="op">=</span> w<span class="op">/</span>lmax</span>
<span id="cb30-4"><a href="#cb30-4"></a><span class="bu">print</span>(<span class="ss">f'The effective temperature of the Sun is approximately </span><span class="sc">{</span>Tsun<span class="sc">:.3f}</span><span class="ss"> K'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The effective temperature of the Sun is approximately 5800.000 K</code></pre>
</div>
</div>
<p>The commonly used value for the emission temperature of the Sun is <span class="math inline">\(T_\odot=5780\)</span> K. Although the peak emission is greenish, the distribution overall produces light that appears yellowish to us, after passing through the atmosphere.</p>
</details>
</section>
<section id="converting-between-wavelength-and-frequency" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="converting-between-wavelength-and-frequency"><span class="header-section-number">1.8.3</span> Converting between wavelength and frequency</h3>
<p>So far we have been using the spectral radiance in terms of wavelength <span class="math inline">\(B_\lambda(\lambda;T).\)</span> It can also be expressed in terms of the frequency of the radiation <span class="math inline">\(B_\nu(\nu;T)\)</span>. Since it is a density across wavelengths, we must be careful when converting between them.</p>
<p><span class="math display">\[
\begin{aligned}
B_\nu(\nu;T)d\nu &amp;= B_\lambda(\lambda;T)d\lambda \\
B_\nu(\nu;T) &amp;= B_\lambda(\lambda(\nu);T) \left|\frac{d\lambda}{d\nu}\right| \\
&amp;= B_\lambda(c/\nu; T) \left|-\frac{c}{\nu^2}\right| \\
  &amp;= \frac{2h\nu^5}{c^3}\left( \frac{1}{\exp\left(\frac{h\nu}{k_BT}\right)-1} \right) \times \frac{c}{\nu^2}
\end{aligned}
\]</span> <span id="eq-wavelength-frequency-conversion"><span class="math display">\[
  B_\nu(\nu;T) = \frac{2h\nu^3}{c^2}\left( \frac{1}{\exp\left(\frac{h\nu}{k_BT}\right)-1}\right)
\tag{1.20}\]</span></span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the conversion derived above, we do not simply do a change of variable using the relationship between frequency and wavelength <span class="math inline">\(\nu = \frac{c}{\lambda}\)</span>! In the conversion from <span class="math inline">\(B_{\lambda}\)</span> to <span class="math inline">\(B_{\nu}\)</span> there is a factor <span class="math display">\[
\left|\frac{d\lambda}{d\nu}\right|=\frac{c}{\nu^2}.
\]</span></p>
<p>This is due to the fact that <span class="math display">\[
\Delta\nu = \nu_2-\nu_1 = \frac{c}{\lambda_2}-\frac{c}{\lambda_1} \neq \frac{c}{\Delta\lambda},
\]</span> which applies also to the infinitesimal case! Therefore we need to consider the derivative <span class="math inline">\(\frac{d\lambda}{d\nu}\)</span>.</p>
</div>
</div>
</section>
<section id="are-stars-really-black-bodies" class="level3" data-number="1.8.4">
<h3 data-number="1.8.4" class="anchored" data-anchor-id="are-stars-really-black-bodies"><span class="header-section-number">1.8.4</span> Are stars really black bodies?</h3>
<p>Let’s take a look at the example of the Solar spectrum of <a href="#fig-solar-irradiance">Figure&nbsp;<span>1.21</span></a>.</p>
<ul>
<li>The Planck black body spectrum is a theoretical prediction for an ideal case, which does not perfectly match the observed one with all its features, but it is usually a good fit.</li>
<li>Light from the Sun is obscured by the atmosphere of the Earth, which absorbs some wavelengths more than others. This is called <em>atmospheric extinction</em>. We will ignore this effect in this course.</li>
<li>There are also <em>spectral lines</em>, gaps in the solar spectrum. More on this later.</li>
</ul>
</section>
<section id="stefan-boltzmann-law" class="level3" data-number="1.8.5">
<h3 data-number="1.8.5" class="anchored" data-anchor-id="stefan-boltzmann-law"><span class="header-section-number">1.8.5</span> Stefan-Boltzmann Law</h3>
<p>The <strong>total (bolometric) luminosity per area</strong> (“radiant emittance” <span class="math inline">\(j=\frac{L}{A}\)</span>) has units of <span class="math inline">\(\mathrm{W\,m}^{-2}\)</span>, and is the spectral radiance integrated over solid angle and wavelength:</p>
<p>The equation for this is known as the Stefan-Boltzmann Law. <span id="eq-stefan-boltzmann-law"><span class="math display">\[
j = \frac{\pi^2 k_B^4 T^4}{60 \hbar^3 c^2}.
\tag{1.21}\]</span></span></p>
<p>This can be written more simply as</p>
<p><span id="eq-stefan-boltzmann-law-sigma"><span class="math display">\[
j = \sigma T^4
\tag{1.22}\]</span></span></p>
<p>where <span id="eq-stefan-boltzmann-const"><span class="math display">\[
\sigma = \frac{\pi^2 k_B^4 }{60 \hbar^3 c^2} = 5.67\times 10^{-8}\mathrm{W\,m^{-2}K^{-4}}
\tag{1.23}\]</span></span> is the Stefan-Boltzmann constant.</p>
</section>
</section>
<section id="stellar-luminosity" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="stellar-luminosity"><span class="header-section-number">1.9</span> Stellar luminosity</h2>
<p>We can multiply <a href="#eq-stefan-boltzmann-const">Equation&nbsp;<span>1.23</span></a> by the surface area to find the total luminosity of a spherical star of radius <span class="math inline">\(R\)</span>.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Total bolometric luminosity
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-total-luminosity"><span class="math display">\[
L = 4\pi R^2 \sigma T^4
\tag{1.24}\]</span></span> This is the most useful form to use in stellar calculations - <strong>remember it</strong>!</p>
</div>
</div>
<p>It allows us to relate <span class="math inline">\(R\)</span>, <span class="math inline">\(L\)</span>, and <span class="math inline">\(T\)</span> for a star.</p>
<ul>
<li>If we know the apparent magnitude and the distance <span class="math inline">\(d\)</span>, then we can find the absolute magnitude using <a href="#eq-apparent-absolute-magnitude">Equation&nbsp;<span>1.14</span></a>.</li>
<li>If we know the absolute magnitude we can find the luminosity using <a href="#eq-absolute-magnitude-scale">Equation&nbsp;<span>1.13</span></a></li>
<li>If we know the luminosity and the temperature we can find the star’s radius using <a href="#eq-total-luminosity">Equation&nbsp;<span>1.24</span></a>!</li>
</ul>
<p>You need to be able to solve these types of problem - <strong>practice it</strong>!</p>
<section id="example-2" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="example-2"><span class="header-section-number">1.9.1</span> <span style="color:#336699;">Example</span></h3>
<p><span class="math inline">\(\epsilon\)</span>-Eridani is a star at <span class="math inline">\(r=3.212\)</span> parsecs distance, with an apparent bolometric magnitude of 3.54 and a peak emission wavelength of 570 nm. What else can we tell about it? Which other quantities can we derive?</p>
<ul>
<li><strong>Absolute bolometric magnitude</strong></li>
</ul>
<p>Knowing the apparent bolometric magnitude <span class="math inline">\(m_\epsilon\)</span> and the distance <span class="math inline">\(r\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
M_\epsilon &amp;= m_\epsilon + 5 - 5\log_{10}r \\
  &amp;= 3.54 + 5 - 5\log_{10}(3.2) \\
  &amp;= 6.0
\end{aligned}
\]</span></p>
<div class="cell" data-execution_count="17">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1"></a><span class="im">from</span> numpy <span class="im">import</span> log10</span>
<span id="cb32-2"><a href="#cb32-2"></a>m <span class="op">=</span> <span class="fl">3.54</span></span>
<span id="cb32-3"><a href="#cb32-3"></a>r <span class="op">=</span> <span class="fl">3.212</span> <span class="co">#pc</span></span>
<span id="cb32-4"><a href="#cb32-4"></a>M <span class="op">=</span> m <span class="op">+</span> <span class="dv">5</span> <span class="op">-</span> <span class="dv">5</span><span class="op">*</span>log10(r)</span>
<span id="cb32-5"><a href="#cb32-5"></a><span class="bu">print</span>(<span class="ss">f'Absolute magnitude: </span><span class="sc">{</span>M<span class="sc">:.1f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Absolute magnitude: 6.0</code></pre>
</div>
</div>
<ul>
<li><strong>Luminosity</strong></li>
</ul>
<p>Knowing the absolute bolometric magnitude <span class="math inline">\(M_\epsilon\)</span> and the zero point luminosity <span class="math inline">\(L_0\)</span> defined in <a href="#eq-zero-point-luminosity">Equation&nbsp;<span>1.10</span></a>, we can use <a href="#eq-absolute-magnitude-scale">Equation&nbsp;<span>1.13</span></a> <span class="math display">\[
L\epsilon = L_0 10^{-0.4 M_\epsilon}
= 3.0128 \times 10^{28} \times 10^{-0.4 \times 6.0}
= 1.2\times 10^{26} \mathrm{W}
\]</span></p>
<div class="cell" data-execution_count="18">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1"></a>L0 <span class="op">=</span> <span class="fl">3.0128E28</span></span>
<span id="cb34-2"><a href="#cb34-2"></a>L <span class="op">=</span> L0<span class="op">*</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="fl">0.4</span><span class="op">*</span>M)</span>
<span id="cb34-3"><a href="#cb34-3"></a><span class="bu">print</span>(<span class="ss">f'Bolometric luminosity </span><span class="sc">{</span>L<span class="sc">:.3e}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Bolometric luminosity 1.193e+26</code></pre>
</div>
</div>
<ul>
<li><strong>Temperature</strong></li>
</ul>
<p>Using Wien’s displacement law (<a href="#eq-wien-displacement-law">Equation&nbsp;<span>1.19</span></a>):</p>
<p><span class="math display">\[
\lambda_{peak} T_\epsilon = 0.0029 \implies
T_\epsilon = \frac{0.0029}{ 570\times 10^{-9}} = T_\epsilon = 5088\,\mathrm{K}
\]</span></p>
<div class="cell" data-execution_count="19">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1"></a>c <span class="op">=</span> <span class="fl">0.0029</span> <span class="co"># m K</span></span>
<span id="cb36-2"><a href="#cb36-2"></a>wavel <span class="op">=</span> <span class="fl">570E-9</span> <span class="co"># m </span></span>
<span id="cb36-3"><a href="#cb36-3"></a>T <span class="op">=</span> c<span class="op">/</span>wavel</span>
<span id="cb36-4"><a href="#cb36-4"></a><span class="bu">print</span>(<span class="ss">f'Temperature: T=</span><span class="sc">{</span>T<span class="sc">:.3e}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Temperature: T=5.088e+03</code></pre>
</div>
</div>
<ul>
<li><strong>Radius</strong></li>
</ul>
<p>Rearranging <a href="#eq-total-luminosity">Equation&nbsp;<span>1.24</span></a>: <span class="math display">\[
R_\epsilon = \sqrt{\frac{L_\epsilon}{4\pi \sigma T^4}}
= \sqrt{\frac{1.3\times 10^{26}}{4\pi \times 5.671\times10^{-8}\times 5088^4}} = 5.00\times 10^{8}\,\mathrm{m}
\]</span></p>
<div class="cell" data-execution_count="20">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1"></a><span class="im">from</span> numpy <span class="im">import</span> sqrt, pi</span>
<span id="cb38-2"><a href="#cb38-2"></a>sigma <span class="op">=</span> <span class="fl">5.671E-8</span></span>
<span id="cb38-3"><a href="#cb38-3"></a>R <span class="op">=</span> sqrt(L<span class="op">/</span>(<span class="dv">4</span><span class="op">*</span>pi<span class="op">*</span>sigma<span class="op">*</span>T<span class="op">**</span><span class="dv">4</span>))</span>
<span id="cb38-4"><a href="#cb38-4"></a><span class="bu">print</span>(<span class="ss">f'Radius: R=</span><span class="sc">{</span>R<span class="sc">:.3e}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Radius: R=4.998e+08</code></pre>
</div>
</div>
</section>
</section>
<section id="recap-1" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="recap-1"><span class="header-section-number">1.10</span> Recap</h2>
<ul>
<li>Black bodies are perfect absorbers and emitters that absorb and emit at all wavelengths</li>
<li><strong>Planck radiation law</strong> gives the shape of the black-body emission spectrum</li>
<li><strong>Wien’s displacement law</strong> relates the peak emission wavelength to the temperature</li>
<li><strong>Stefan-Boltzmann law</strong> can be used to find the total power radiated by a black body</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./SP1.2_-_Stellar_classification.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Classifying stars</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>